Ext.define('MetExplore.Application', {
    name: 'MetExplore',

    extend: 'Ext.app.Application',

    views: ['Viewport',
        'V_SidePanel',
        'V_MappingVizPanel',
        'V_MainPanel',
        'V_BannerPanel',
        'menu.V_AboutMenu',
        'menu.V_ExportMenu',
        'menu.V_TestMenu',
        'menu.V_GraphModelling',
        'menu.V_MappingMenu',
        //'menu.V_MeSHMenu',
        'menu.V_OmicsMenu',
        'menu.V_ToolMenu',
        //'tree.V_treeFilter',
        'panel.V_PanelMappingViz',
        'panel.V_dataBioSource',
        'panel.V_panelVotes',
        'panel.V_PanelVizGPR',
        'button.V_JavaApplicationMenuItem',
        'button.V_CytoscapeWebStartButton',
        'chart.V_ChartPathwayCompleteness',
        'main.V_ProjectPanel',
        'main.V_CurationPanel',
        'main.V_MetabolomeProperties',
        'main.V_NetworksPanel',
        'main.V_UserPanel',
        'main.V_NetworkData',
        'form.V_GraphRankUI',
        //'form.V_MeSHUI',
        //'form.V_MeSHPairMetricsUI',
        //'form.V_Metab2MeSHUI',
        //'form.V_SelectMeSH',
        //'form.V_SelectMeSHPairMetrics',
        'form.V_SelectMetabolites',
        'form.V_SelectCompartment',
        'form.V_SelectBioSources',
        'form.V_SelectInsertOrganism',
        'form.V_SelectMyBioSources',
        'form.V_SelectMapping',
        'form.V_SelectInsertReaction',
        'form.V_AddReactionForm',
        'form.V_SelectInsertEnzymes',
        'form.V_AddGenericForm',
        'form.V_AddPathwayForm',
        'form.V_LoginForm',
        'form.V_SelectProjectBioSources',
        'form.V_SelectInsertProtein',
        'form.V_Map',
        'form.V_MapMulti',
        'form.V_IdentifierMatcher',
        'form.V_MapGene',
        'form.V_SelectProteins',
        'form.V_ManageProject',
        'form.V_SelectUsers',
        'form.V_SelectInsertGeneric',
        'form.V_MetaboliteSearch',
        'form.V_updateBioSource',
        'form.V_SelectPathway',
        'form.V_AddBiblioForm',
        'form.V_ReactionForm',
        'form.V_EditUserProfile',
        'form.V_Annotation_TabFile',
        'form.V_SelectEnzymes',
        'form.V_AddBioSourceForm',
        'form.V_SelectInsertPathway',
        'form.V_SelectInsertCompartment',
        'form.V_MetaboliteAnnotationFromFile',
        'form.V_SelectReactions',
        'form.V_AddEnzymeForm',
        'form.V_SelectElement',
        'form.V_EditTodoAction',
        'form.V_SelectTabDataColumn',
        'form.V_AddGeneForm',
        'form.V_SelectReactionStatus',
        'form.V_AddProteinForm',
        'form.V_JavaApplicationParametersForm',
        'form.V_ReactionCreate',
        'form.V_SelectGenes',
        'form.V_DetailsComment',
        'form.V_DetailsAttachment',
        'form.V_SelectOrganism',
        'form.V_SelectInsertGenes',
        'form.V_AddCompartmentForm',
        'form.V_ReactionAnnotationFromFile',
        'form.V_AddMetaboliteForm',
        'form.V_ConfirmAddUserToProject',
        'form.V_ShareBioSource',
        'form.V_AddUserToProject',
        'form.V_ChooseRightsOnUserProject',
        'window.V_WindowInfoGene',
        'window.V_WindowInfoGeneric',
        'window.V_WindowInfoJob',
        'window.V_WindowInfoPubMed',
        'window.V_WindowInfoMetabolite',
        'window.V_WindowInfoEnzyme',
        'window.V_WindowInfoProtein',
        'window.V_WindowInfoReaction',
        'window.V_WindowStatisticsPathway',
        'window.V_CytoscapeLaunchWindow',
        'window.V_WindowInfoPathway',
        'window.V_WindowInfoBioSource',
        'grid.V_gridPathwaysInReaction',
        'grid.V_GridDetailsVotes',
        'grid.V_gridAdd',
        //'grid.V_gridMeSHPairMetrics',
        'grid.V_gridProtein',
        'grid.V_gridEnzyme',
        'grid.V_GridJobs',
        'grid.V_gridUserProjects',
        'grid.V_GridHistory',
        'grid.V_gridReactionBiblio',
        'grid.V_gridBiblioLinks',
        'grid.V_gridReactionsInPathway',
        'grid.V_gridDelReaction',
        'grid.V_gridGenesInPathway',
        'grid.V_gridReaction',
        'grid.V_gridMetaboliteIds',
        'grid.V_gridAddReactionFromFile',
        'grid.V_GridTodoList',
        'grid.V_gridCart',
        'grid.V_gridFilter',
        'grid.V_gridMyBioSource',
        'grid.V_gridGene',
        'grid.V_gridObjectComment',
        'grid.V_GenericGrid',
        'grid.V_gridBioSource',
        'grid.V_gridAttachment',
        'grid.V_gridMetabolite',
        'grid.V_gridAddMetaboliteFromFile',
        'grid.V_GridUsersInProject',
        'grid.V_GridDetailsHistory',
        'grid.V_gridData',
        'grid.V_gridDataGene',
        'grid.V_gridDataIdentifiers',
        'grid.V_gridAnnotation',
        'grid.V_gridBioSourceInfo',
        'grid.V_gridPathway',
        'grid.V_gridCompartment',
        'grid.V_GridUserProjectBioSource',
        'grid.V_gridGenesInReaction'
    ],

    controllers: [ /* User and Project panel: */

        'userAndProject.C_TodoList', 'userAndProject.C_EditTodoAction',
        'userAndProject.C_UserProjects', 'userAndProject.C_ManageProject', 'userAndProject.C_GridHistory',
        'userAndProject.C_EditProfile', 'userAndProject.C_ProjectPanel', 'userAndProject.C_ConfirmAddUserToProject',
        'userAndProject.C_GridUsersInProject', 'userAndProject.C_ChooseRightsOnUserProject', 'userAndProject.C_HistoryReport',
        'C_HelpRedirection',
        /* BioSource */
        'C_BioSource',
        'C_gridBioSource',
        'C_updateBioSource',
        /* Environnement application */
        'C_User',
        'C_SidePanel',
        'C_MappingVizPanel',
        'C_Session',
        //'C_SelectMeSH',
        'C_DisplayCytoscapeWebStartWindow',
        'C_DisplayJavaApplicationParameters',
        'C_ReportTableSelection',
        'C_LaunchJavaApplication',
        'C_AutoloadData',
        /* data network */
        'C_NetworkData',
        'C_gridFilter',
        'C_gridCart',
        'C_gridReaction',
        'C_GenericGrid',
        'C_gridMetabolite',
        'C_gridPathway',
        'C_gridCompartment',
        'C_gridEnzyme',
        'C_gridProtein',
        'C_gridGene',
        //'C_gridMeSHPairMetrics',
        /* Statistics */
        'statistics.C_WindowStatisticsPathway',
        'statistics.C_WindowStatisticsReaction',
        /* creation */
        'C_AddMetaboliteForm',
        'C_AddPathwayForm',
        'C_AddReactionForm',
        'C_SelectInsertGeneric',
        'C_AddCompartmentForm',
        'C_AddBioSourceForm',
        'C_AddEnzymeForm',
        'C_AddProteinForm',
        'C_AddGeneForm',
        'C_SelectElement',
        'C_gridAddReactionFromFile',
        'C_gridBiblio',
        /* mapping */
        'C_gridData',
        'C_gridDataIdentifiers',
        'C_gridDataGene',
        'C_Map',
        'C_MapMulti',
        'C_MapGene',
        'C_GraphRank',
        //'C_MeSH',
       // 'C_MeSHPairMetrics',
        //'C_Metab2MeSH',
        'C_SelectMapping',
        /* toolbox */
        'C_gridDataIdentifiers',
        'C_IdentifierMatcher',
        /* report */
        // 'C_ReportPanel',
        /* annotation */
        'C_CurationPanel',
        'C_gridAnnotation',
        'C_Match',
        'C_gridAdd',
        'C_ReactionAnnotationFromFile',
        /* graph */
        'C_NetworksPanel',
        'C_gridBiblioLinks',
        /* windowInfo */
        'windowInfo.C_WindowInfoGeneric',
        'windowInfo.C_WindowInfoPubMed',
        'windowInfo.C_WindowInfoMetabolite', 'windowInfo.C_panelVotes',
        'windowInfo.C_HideColumnInWindowInfo', 'windowInfo.C_PanelVizGPR',
        'windowInfo.C_dataBiosource',
        /* comments */
        'comments.C_gridObjectComment', 'comments.C_DetailsComment',
        'comments.C_gridAttachment', 'comments.C_DetailsAttachment',
        /* */
        'C_OpenLinkInDBWebSite', 'MetExplore.controller.C_ExportExcel',
        /* jobs */
        'jobs.C_ReloadJobs', 'jobs.C_DeleteJob', 'jobs.C_ViewResult', 'jobs.C_ViewLog',

    ],

    stores: [ /* User and Project panel: */
        'S_TodoList', 'S_UserProjects', 'S_UsersInProject', 'S_Access', 'S_History', 'S_UserHistory', 'S_ProjectHistory',
        'S_Filter',
        /* BioSource */
        'S_BioSource',
        'S_MyBioSource',
        'S_Organism',
        'S_gridBioSource',
        'S_BioSourceInfo',
        'S_BioSourceData',
        /* Environnement application */
        'S_UserMenu',
        'S_Application',
        'S_LocalstorageUrlAccess',
        'S_LocalstorageData',
        //'S_ApplicationComponent',
        'S_InchiPeakForest',
        'S_TreeUsers',
        /* data network */
        'S_CompartmentInBioSource', 'S_Pathway', 'S_Reaction',
        'S_Metabolite', 'S_Enzyme', 'S_Protein', 'S_Gene',
        'S_ReactionGPR',
        'S_ReactionEquation',
        //'S_MeSH4Select',
        //'S_MeSHPairMetrics',
        //'S_MeSHPairMetricsValues',
        'S_MetaboliteInchiSvg',
        'S_MetaboliteInchikey',
        'S_MetaboliteDBIds',
        'S_MetaboliteDBName',
        'S_MetaboliteIds',
        /* annotation & creation */
        'S_AnnotationPathway',
        'S_AnnotationReaction',
        'S_AnnotationMetabolite',
        'S_ReactionCreation',
        /* status & comment & biblio */
        'S_Comment',
        'S_Attachment',
        'S_Biblio',
        'S_ReactionBiblio',
        /* mapping */
        'S_DataMultiMapping','S_DataMapping', 'S_PathwayMapped',
        'S_DataTab',
        'S_MappingInfo',
        'S_Condition',
        'S_ColorMapping',
        /*matching*/
        'S_MatchingInfo',
        /* graph */
        'S_NetworkVizSession', 'S_LinkReactionMetabolite',
        'S_MetaboliteIdentifiers', 'S_NetworkField', 'S_Cart',
        'S_Scale',
        /* Stores of windowInfo */
        'S_ReactionIdentifiers', 'S_ReactionsInPathway', 'S_ReactionPathway', 'S_GenesInPathway', 'S_DetailsVotes',
        /* */
        'S_MetaboliteTopo', 'S_Users',
        /* jobs */
        'S_Analyses',
        /* Curation */
        'S_ModelIdentifier',
        /*feature config*/
       'S_Feature',
        /*identifiers*/
        'S_IdentifiersDBName','S_Identifiersgit',
        'S_IdentifiersGene','S_IdentifiersReaction','S_IdentifiersMetabolite',
        'S_StatBioSource'
    ]

});