<?php

if(! isset($P_idReaction)) {$P_idReaction = "";}
if(! isset($P_idPathway)) {$P_idPathway = "";}

// "CONCAT(CONCAT(Organism.name,' - '),CONCAT(BioSource.strain,CONCAT(' - ',BioSource.nameBioSource))) AS NomComplet";
$R_BioSource="SELECT DISTINCT id, nameBioSource FROM BioSource";

/************************
**	Pathway
************************/
$R_Pathway_ListidGene=			"SELECT DISTINCT Pathway.id AS idInBio, Pathway.id AS id, Pathway.name AS name, Pathway.dbIdentifier AS dbIdentifier FROM Pathway, ReactionInPathway, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource, GeneCodesForProtein, GeneInBioSource WHERE  Pathway.id=ReactionInPathway.idPathway  AND ReactionInPathway.idReactionBioSource = ReactionInBioSource.id AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND GeneCodesForProtein.idProteinInBioSource = ProteinInBioSource.id AND GeneCodesForProtein.idGeneInBioSource = GeneInBioSource.id AND ( GeneInBioSource.idGene IN ($P_Listid) AND ReactionInBioSource.idBioSource = $P_idBioSource)";
$R_Pathway_ListidProtein=		"SELECT DISTINCT Pathway.id AS idInBio, Pathway.id AS id, Pathway.name AS name, Pathway.dbIdentifier AS dbIdentifier FROM Pathway, ReactionInPathway, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource WHERE  Pathway.id=ReactionInPathway.idPathway AND ReactionInPathway.idReactionBioSource = ReactionInBioSource.id AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInEnzyme.idProteinInBioSource = ProteinInBioSource.id AND ( ProteinInBioSource.idProtein IN ($P_Listid) AND ReactionInBioSource.idBioSource = $P_idBioSource)";
$R_Pathway_ListidEnzyme=		"SELECT DISTINCT Pathway.id AS idInBio, Pathway.id AS id, Pathway.name AS name, Pathway.dbIdentifier AS dbIdentifier FROM Pathway, ReactionInPathway, ReactionInBioSource, Catalyses, EnzymeInBioSource WHERE  Pathway.id=ReactionInPathway.idPathway AND ReactionInPathway.idReactionBioSource = ReactionInBioSource.id AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.idEnzyme IN ($P_Listid) AND ReactionInBioSource.idBioSource = $P_idBioSource";
$R_Pathway_ListidMetabLeft=		"SELECT DISTINCT Pathway.id AS idInBio, Pathway.id AS id, Pathway.name AS name, Pathway.dbIdentifier AS dbIdentifier FROM Pathway, ReactionInPathway, ReactionInBioSource, Reaction, LeftParticipant,  Metabolite, MetaboliteInBioSource WHERE  Pathway.id=ReactionInPathway.idPathway AND ReactionInPathway.idReactionBioSource = ReactionInBioSource.id AND LeftParticipant.idMetabolite = Metabolite.id AND LeftParticipant.idReaction = Reaction.id AND ReactionInBioSource.idReaction = Reaction.id AND MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idMetabolite  IN ($P_Listid) AND ReactionInBioSource.idBioSource = $P_idBioSource";
$R_Pathway_ListidMetabRight=	"SELECT DISTINCT Pathway.id AS idInBio, Pathway.id AS id, Pathway.name AS name, Pathway.dbIdentifier AS dbIdentifier FROM Pathway, ReactionInPathway, ReactionInBioSource, Reaction, RightParticipant, Metabolite, MetaboliteInBioSource WHERE  Pathway.id=ReactionInPathway.idPathway AND ReactionInPathway.idReactionBioSource = ReactionInBioSource.id AND RightParticipant.idMetabolite= Metabolite.id AND RightParticipant.idReaction= Reaction.id AND ReactionInBioSource.idReaction = Reaction.id AND MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite IN ($P_Listid) AND ReactionInBioSource.idBioSource = $P_idBioSource ";
if(isset($R_Pathway_ListidMetabLeft) && isset($R_Pathway_ListidMetabRight)) {
	$R_Pathway_ListidMetabolite=  "$R_Pathway_ListidMetabLeft UNION $R_Pathway_ListidMetabRight";
}
$R_Pathway_ListidReaction=		"SELECT DISTINCT Pathway.id AS idInBio, Pathway.id AS id, Pathway.name AS name, Pathway.dbIdentifier AS dbIdentifier FROM Pathway, ReactionInPathway, ReactionInBioSource WHERE Pathway.id=ReactionInPathway.idPathway  AND ReactionInPathway.idReactionBioSource = ReactionInBioSource.id AND ReactionInBioSource.idReaction IN ($P_Listid) AND ReactionInBioSource.idBioSource = $P_idBioSource";
$R_Pathway_ListidPathway=		"SELECT DISTINCT Pathway.id AS idInBio, Pathway.id AS id, Pathway.name AS name, Pathway.dbIdentifier AS dbIdentifier FROM Pathway, ReactionInPathway, ReactionInBioSource WHERE Pathway.id=ReactionInPathway.idPathway  AND ReactionInPathway.idReactionBioSource = ReactionInBioSource.id AND ReactionInBioSource.idBioSource = $P_idBioSource AND ReactionInPathway.idPathway IN ($P_Listid)";
//$R_PathwayFromReaction=						"SELECT DISTINCT Pathway.id AS idInBio, Pathway.id AS id, Pathway.name AS name, Pathway.dbIdentifier AS dbIdentifier, Pathway.confidence AS confidence FROM Pathway, ReactionInPathway, ReactionInBioSource WHERE Pathway.id=ReactionInPathway.idPathway  AND ReactionInPathway.idReactionBioSource = ReactionInBioSource.id AND ReactionInBioSource.idBioSource = $P_idBioSource";
$R_PathwayFromReaction="SELECT DISTINCT Pathway.id AS idInBio, Pathway.id AS id, Pathway.name AS name, Pathway.dbIdentifier AS dbIdentifier FROM Pathway, ReactionInPathway, ReactionInBioSource WHERE Pathway.id=ReactionInPathway.idPathway  AND ReactionInPathway.idReactionBioSource = ReactionInBioSource.id AND ReactionInBioSource.idBioSource = $P_idBioSource ORDER BY name";

//$R_PathwayInBioSource="SELECT DISTINCT Pathway.id AS idInBio, Pathway.id AS id, Pathway.name AS name, Pathway.dbIdentifier AS dbIdentifier, Pathway.confidence AS confidence FROM Pathway, PathwayInBioSource WHERE Pathway.id=PathwayInBioSource.idPathway AND PathwayInBioSource.idBioSource=$P_idBioSource";
$R_PathwayInBioSource="SELECT DISTINCT Pathway.id AS idInBio, Pathway.id AS id, Pathway.name AS name, Pathway.dbIdentifier AS dbIdentifier FROM Pathway, PathwayInBioSource WHERE Pathway.id=PathwayInBioSource.idPathway AND PathwayInBioSource.idBioSource=$P_idBioSource ORDER BY name";

$R_Pathway="($R_PathwayFromReaction) UNION ($R_PathwayInBioSource)";

/************************
**	Reaction
************************/
$R_Reaction_ListidGene=			"SELECT ReactionInBioSource.id AS idInBio, Reaction.id AS id, Reaction.name AS name, Reaction.ec AS ec, Reaction.dbIdentifier AS dbIdentifier, ReactionInBioSource.reversible AS reversible, ReactionInBioSource.hole AS hole, ReactionInBioSource.upperBound AS upperBound, ReactionInBioSource.lowerBound AS lowerBound FROM Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource, GeneCodesForProtein, GeneInBioSource WHERE  Reaction.id = ReactionInBioSource.idReaction AND ReactionInBioSource.idBioSource = $P_idBioSource AND ReactionInBioSource.id = Catalyses.idReactionInBioSource AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND GeneCodesForProtein.idProteinInBioSource = ProteinInBioSource.id AND GeneCodesForProtein.idGeneInBioSource = GeneInBioSource.id AND GeneInBioSource.idGene IN ($P_Listid)";
$R_Reaction_ListidProtein=		"SELECT ReactionInBioSource.id AS idInBio, Reaction.id AS id, Reaction.name AS name, Reaction.ec AS ec, Reaction.dbIdentifier AS dbIdentifier, ReactionInBioSource.reversible AS reversible, ReactionInBioSource.hole AS hole, ReactionInBioSource.upperBound AS upperBound, ReactionInBioSource.lowerBound AS lowerBound FROM Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource WHERE  Reaction.id = ReactionInBioSource.idReaction AND ReactionInBioSource.idBioSource = $P_idBioSource AND ReactionInBioSource.id = Catalyses.idReactionInBioSource AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInEnzyme.idProteinInBioSource = ProteinInBioSource.id AND ProteinInBioSource.idProtein IN ($P_Listid)";
$R_Reaction_ListidEnzyme=		"SELECT ReactionInBioSource.id AS idInBio, Reaction.id AS id, Reaction.name AS name, Reaction.ec AS ec, Reaction.dbIdentifier AS dbIdentifier, ReactionInBioSource.reversible AS reversible, ReactionInBioSource.hole AS hole, ReactionInBioSource.upperBound AS upperBound, ReactionInBioSource.lowerBound AS lowerBound FROM Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource WHERE  Reaction.id = ReactionInBioSource.idReaction AND ReactionInBioSource.idBioSource = $P_idBioSource AND ReactionInBioSource.id = Catalyses.idReactionInBioSource AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id  AND EnzymeInBioSource.idEnzyme IN ($P_Listid)";
$R_Reaction_ListidMetabLeft=	"SELECT ReactionInBioSource.id AS idInBio, Reaction.id AS id, Reaction.name AS name, Reaction.ec AS ec, Reaction.dbIdentifier AS dbIdentifier, ReactionInBioSource.reversible AS reversible, ReactionInBioSource.hole AS hole, ReactionInBioSource.upperBound AS upperBound, ReactionInBioSource.lowerBound AS lowerBound FROM Reaction, ReactionInBioSource, Metabolite, LeftParticipant  WHERE  Reaction.id = ReactionInBioSource.idReaction AND ReactionInBioSource.idBioSource = $P_idBioSource AND Metabolite.id = LeftParticipant.idMetabolite  AND LeftParticipant.idReaction = Reaction.id  AND Metabolite.id IN ($P_Listid)";
$R_Reaction_ListidMetabRight=	"SELECT ReactionInBioSource.id AS idInBio, Reaction.id AS id, Reaction.name AS name, Reaction.ec AS ec, Reaction.dbIdentifier AS dbIdentifier, ReactionInBioSource.reversible AS reversible, ReactionInBioSource.hole AS hole, ReactionInBioSource.upperBound AS upperBound, ReactionInBioSource.lowerBound AS lowerBound FROM Reaction, ReactionInBioSource, Metabolite, RightParticipant WHERE  Reaction.id = ReactionInBioSource.idReaction AND ReactionInBioSource.idBioSource = $P_idBioSource AND Metabolite.id = RightParticipant.idMetabolite AND RightParticipant.idReaction = Reaction.id AND Metabolite.id IN ($P_Listid)";
if(isset($R_Reaction_ListidMetabLeft) && isset($R_Reaction_ListidMetabRight)) {
	$R_Reaction_ListidMetabolite=	"$R_Reaction_ListidMetabLeft UNION $R_Reaction_ListidMetabRight";
}
$R_Reaction_ListidReaction=		"SELECT ReactionInBioSource.id AS idInBio, Reaction.id AS id, Reaction.name AS name, Reaction.ec AS ec, Reaction.dbIdentifier AS dbIdentifier, ReactionInBioSource.reversible AS reversible, ReactionInBioSource.hole AS hole, ReactionInBioSource.upperBound AS upperBound, ReactionInBioSource.lowerBound AS lowerBound FROM Reaction, ReactionInBioSource  WHERE  Reaction.id = ReactionInBioSource.idReaction AND ReactionInBioSource.idBioSource = $P_idBioSource AND ReactionInBioSource.idReaction IN ($P_Listid)";
$R_Reaction_ListidPathway=		"SELECT ReactionInBioSource.id AS idInBio, Reaction.id AS id, Reaction.name AS name, Reaction.ec AS ec, Reaction.dbIdentifier AS dbIdentifier, ReactionInBioSource.reversible AS reversible, ReactionInBioSource.hole AS hole, ReactionInBioSource.upperBound AS upperBound, ReactionInBioSource.lowerBound AS lowerBound FROM Reaction, ReactionInBioSource, ReactionInPathway WHERE Reaction.id = ReactionInBioSource.idReaction AND ReactionInPathway.idReactionBioSource = ReactionInBioSource.id AND ReactionInBioSource.idReaction = Reaction.id AND ReactionInPathway.idPathway IN ($P_Listid) AND ReactionInBioSource.idBioSource = $P_idBioSource";
$R_Reaction=					"SELECT ReactionInBioSource.id AS idInBio, Reaction.id AS id, Reaction.name AS name, Reaction.ec AS ec, Reaction.dbIdentifier AS dbIdentifier, ReactionInBioSource.reversible AS reversible, ReactionInBioSource.hole AS hole, ReactionInBioSource.upperBound AS upperBound, ReactionInBioSource.lowerBound AS lowerBound, ReactionInBioSource.inConflictWith AS inConflictWith FROM Reaction, ReactionInBioSource  WHERE  Reaction.id = ReactionInBioSource.idReaction AND ReactionInBioSource.idBioSource = $P_idBioSource ORDER BY name";
//$R_Reaction_Compart=			"SELECT DISTINCT ReactionInBioSource.id AS idInBio, Reaction.id AS id, Reaction.name AS name, Reaction.ec AS ec, Reaction.dbIdentifier AS dbIdentifier, ReactionInBioSource.reversible AS reversible, ReactionInBioSource.hole AS hole, ReactionInBioSource.upperBound AS upperBound, ReactionInBioSource.lowerBound AS lowerBound FROM Reaction, ReactionInBioSource, ReactionInCompartment  WHERE  Reaction.id = ReactionInBioSource.idReaction AND ReactionInCompartment.idReaction= Reaction.id AND ReactionInBioSource.idBioSource = $P_idBioSource AND ReactionInCompartment.idCompartmentInBioSource IN ($P_Listid)";

/************************
**	Metabolite Left
************************/
$R_MetabLeft_ListidGene=		"SELECT DISTINCT Metabolite.id AS idInBio, Metabolite.id AS id, Metabolite.name AS name, Metabolite.chemicalFormula AS chemicalFormula, Metabolite.dbIdentifier AS dbIdentifier, Metabolite.smiles AS smiles, Metabolite.caas AS caas, Metabolite.weight AS weight, Metabolite.exactNeutralMass AS exactNeutralMass, Metabolite.averageMass AS averageMass, Metabolite.generic AS generic, MetaboliteInBioSource.sideCompound AS sideCompound FROM Metabolite, MetaboliteInBioSource, LeftParticipant, Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource, GeneCodesForProtein, GeneInBioSource WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idReaction = Reaction.id AND LeftParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND LeftParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND GeneCodesForProtein.idProteinInBioSource = ProteinInBioSource.id AND GeneCodesForProtein.idGeneInBioSource = GeneInBioSource.id AND GeneInBioSource.idGene IN ($P_Listid)";
$R_MetabLeft_ListidProtein=		"SELECT DISTINCT Metabolite.id AS idInBio, Metabolite.id AS id, Metabolite.name AS name, Metabolite.chemicalFormula AS chemicalFormula, Metabolite.dbIdentifier AS dbIdentifier, Metabolite.smiles AS smiles, Metabolite.caas AS caas, Metabolite.weight AS weight, Metabolite.exactNeutralMass AS exactNeutralMass, Metabolite.averageMass AS averageMass, Metabolite.generic AS generic, MetaboliteInBioSource.sideCompound AS sideCompound FROM Metabolite, MetaboliteInBioSource, LeftParticipant, Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idMetabolite = Metabolite.id AND LeftParticipant.idReaction = Reaction.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND LeftParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND ProteinInBioSource.idProtein IN ($P_Listid)";
$R_MetabLeft_ListidEnzyme=		"SELECT DISTINCT Metabolite.id AS idInBio, Metabolite.id AS id, Metabolite.name AS name, Metabolite.chemicalFormula AS chemicalFormula, Metabolite.dbIdentifier AS dbIdentifier, Metabolite.smiles AS smiles, Metabolite.caas AS caas, Metabolite.weight AS weight, Metabolite.exactNeutralMass AS exactNeutralMass, Metabolite.averageMass AS averageMass, Metabolite.generic AS generic, MetaboliteInBioSource.sideCompound AS sideCompound FROM Metabolite, MetaboliteInBioSource, LeftParticipant, Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idMetabolite = Metabolite.id AND LeftParticipant.idReaction = Reaction.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND LeftParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.idEnzyme IN ($P_Listid)";
$R_MetabLeft_ListidReaction=	"SELECT DISTINCT Metabolite.id AS idInBio, Metabolite.id AS id, Metabolite.name AS name, Metabolite.chemicalFormula AS chemicalFormula, Metabolite.dbIdentifier AS dbIdentifier, Metabolite.smiles AS smiles, Metabolite.caas AS caas, Metabolite.weight AS weight, Metabolite.exactNeutralMass AS exactNeutralMass, Metabolite.averageMass AS averageMass, Metabolite.generic AS generic, MetaboliteInBioSource.sideCompound AS sideCompound FROM Metabolite, MetaboliteInBioSource, LeftParticipant WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND LeftParticipant.idReaction IN ($P_Listid)";
$R_MetabLeft_ListidMetabolite=	"SELECT DISTINCT Metabolite.id AS idInBio, Metabolite.id AS id, Metabolite.name AS name, Metabolite.chemicalFormula AS chemicalFormula, Metabolite.dbIdentifier AS dbIdentifier, Metabolite.smiles AS smiles, Metabolite.caas AS caas, Metabolite.weight AS weight, Metabolite.exactNeutralMass AS exactNeutralMass, Metabolite.averageMass AS averageMass, Metabolite.generic AS generic, MetaboliteInBioSource.sideCompound AS sideCompound FROM Metabolite, MetaboliteInBioSource, LeftParticipant WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND Metabolite.id IN ($P_Listid)";
$R_MetabLeft_idReaction=	    "SELECT DISTINCT Metabolite.id AS idInBio, Metabolite.id AS id, Metabolite.name AS name, Metabolite.chemicalFormula AS chemicalFormula, Metabolite.dbIdentifier AS dbIdentifier, Metabolite.smiles AS smiles, Metabolite.caas AS caas, Metabolite.weight AS weight, Metabolite.exactNeutralMass AS exactNeutralMass, Metabolite.averageMass AS averageMass, Metabolite.generic AS generic, MetaboliteInBioSource.sideCompound AS sideCompound FROM Metabolite, MetaboliteInBioSource, LeftParticipant WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND LeftParticipant.idReaction = $P_idReaction";
$R_MetabLeft_ListidPathway=		"SELECT DISTINCT Metabolite.id AS idInBio, Metabolite.id AS id, Metabolite.name AS name, Metabolite.chemicalFormula AS chemicalFormula, Metabolite.dbIdentifier AS dbIdentifier, Metabolite.smiles AS smiles, Metabolite.caas AS caas, Metabolite.weight AS weight, Metabolite.exactNeutralMass AS exactNeutralMass, Metabolite.averageMass AS averageMass, Metabolite.generic AS generic, MetaboliteInBioSource.sideCompound AS sideCompound FROM Metabolite, MetaboliteInBioSource, LeftParticipant, Reaction, ReactionInBioSource, ReactionInPathway WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND LeftParticipant.idReaction = Reaction.id AND LeftParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND ReactionInBioSource.id=ReactionInPathway.idReactionBioSource AND ReactionInPathway.idPathway IN ($P_Listid)";
$R_MetabLeft=					"SELECT DISTINCT Metabolite.id AS idInBio, Metabolite.id AS id, Metabolite.name AS name, Metabolite.chemicalFormula AS chemicalFormula, Metabolite.dbIdentifier AS dbIdentifier, Metabolite.smiles AS smiles, Metabolite.caas AS caas, Metabolite.weight AS weight, Metabolite.exactNeutralMass AS exactNeutralMass, Metabolite.averageMass AS averageMass, Metabolite.generic AS generic, MetaboliteInBioSource.sideCompound AS sideCompound FROM Metabolite, MetaboliteInBioSource, LeftParticipant WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource";
$R_MetabLeft_idPathway=	 		"SELECT DISTINCT Metabolite.id AS id FROM Metabolite, MetaboliteInBioSource, LeftParticipant, Reaction, ReactionInBioSource, ReactionInPathway WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idMetabolite = Metabolite.id AND ReactionInBioSource.idBioSource = $P_idBioSource AND LeftParticipant.idReaction = Reaction.id AND LeftParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND ReactionInBioSource.id=ReactionInPathway.idReactionBioSource AND ReactionInPathway.idPathway = $P_idPathway";

/************************
**	Metabolite Right
************************/
$R_MetabRight_ListidGene=		"SELECT DISTINCT Metabolite.id AS idInBio, Metabolite.id AS id, Metabolite.name AS name, Metabolite.chemicalFormula AS chemicalFormula, Metabolite.dbIdentifier AS dbIdentifier, Metabolite.smiles AS smiles, Metabolite.caas AS caas, Metabolite.weight AS weight, Metabolite.exactNeutralMass AS exactNeutralMass, Metabolite.averageMass AS averageMass, Metabolite.generic AS generic, MetaboliteInBioSource.sideCompound AS sideCompound FROM Metabolite, MetaboliteInBioSource, RightParticipant, Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource, GeneCodesForProtein, GeneInBioSource WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND RightParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND GeneCodesForProtein.idProteinInBioSource = ProteinInBioSource.id AND GeneCodesForProtein.idGeneInBioSource = GeneInBioSource.id AND GeneInBioSource.idGene IN ($P_Listid)";
$R_MetabRight_ListidProtein=	"SELECT DISTINCT Metabolite.id AS idInBio, Metabolite.id AS id, Metabolite.name AS name, Metabolite.chemicalFormula AS chemicalFormula, Metabolite.dbIdentifier AS dbIdentifier, Metabolite.smiles AS smiles, Metabolite.caas AS caas, Metabolite.weight AS weight, Metabolite.exactNeutralMass AS exactNeutralMass, Metabolite.averageMass AS averageMass, Metabolite.generic AS generic, MetaboliteInBioSource.sideCompound AS sideCompound FROM Metabolite, MetaboliteInBioSource, RightParticipant, Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND RightParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND ProteinInBioSource.idProtein IN ($P_Listid)";
$R_MetabRight_ListidEnzyme=		"SELECT DISTINCT Metabolite.id AS idInBio, Metabolite.id AS id, Metabolite.name AS name, Metabolite.chemicalFormula AS chemicalFormula, Metabolite.dbIdentifier AS dbIdentifier, Metabolite.smiles AS smiles, Metabolite.caas AS caas, Metabolite.weight AS weight, Metabolite.exactNeutralMass AS exactNeutralMass, Metabolite.averageMass AS averageMass, Metabolite.generic AS generic, MetaboliteInBioSource.sideCompound AS sideCompound FROM Metabolite, MetaboliteInBioSource, RightParticipant, Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND RightParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.idEnzyme IN ($P_Listid)";
$R_MetabRight_ListidReaction=	"SELECT DISTINCT Metabolite.id AS idInBio, Metabolite.id AS id, Metabolite.name AS name, Metabolite.chemicalFormula AS chemicalFormula, Metabolite.dbIdentifier AS dbIdentifier, Metabolite.smiles AS smiles, Metabolite.caas AS caas, Metabolite.weight AS weight, Metabolite.exactNeutralMass AS exactNeutralMass, Metabolite.averageMass AS averageMass, Metabolite.generic AS generic, MetaboliteInBioSource.sideCompound AS sideCompound FROM Metabolite, MetaboliteInBioSource, RightParticipant WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND RightParticipant.idReaction IN ($P_Listid)";
$R_MetabRight_ListidMetabolite=	"SELECT DISTINCT Metabolite.id AS idInBio, Metabolite.id AS id, Metabolite.name AS name, Metabolite.chemicalFormula AS chemicalFormula, Metabolite.dbIdentifier AS dbIdentifier, Metabolite.smiles AS smiles, Metabolite.caas AS caas, Metabolite.weight AS weight, Metabolite.exactNeutralMass AS exactNeutralMass, Metabolite.averageMass AS averageMass, Metabolite.generic AS generic, MetaboliteInBioSource.sideCompound AS sideCompound FROM Metabolite, MetaboliteInBioSource, RightParticipant WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND Metabolite.id IN ($P_Listid)";
$R_MetabRight_idReaction=	    "SELECT DISTINCT Metabolite.id AS idInBio, Metabolite.id AS id, Metabolite.name AS name, Metabolite.chemicalFormula AS chemicalFormula, Metabolite.dbIdentifier AS dbIdentifier, Metabolite.smiles AS smiles, Metabolite.caas AS caas, Metabolite.weight AS weight, Metabolite.exactNeutralMass AS exactNeutralMass, Metabolite.averageMass AS averageMass, Metabolite.generic AS generic, MetaboliteInBioSource.sideCompound AS sideCompound FROM Metabolite, MetaboliteInBioSource, RightParticipant WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND RightParticipant.idReaction = $P_idReaction";
$R_MetabRight_ListidPathway=	"SELECT DISTINCT Metabolite.id AS idInBio, Metabolite.id AS id, Metabolite.name AS name, Metabolite.chemicalFormula AS chemicalFormula, Metabolite.dbIdentifier AS dbIdentifier, Metabolite.smiles AS smiles, Metabolite.caas AS caas, Metabolite.weight AS weight, Metabolite.exactNeutralMass AS exactNeutralMass, Metabolite.averageMass AS averageMass, Metabolite.generic AS generic, MetaboliteInBioSource.sideCompound AS sideCompound FROM Metabolite, MetaboliteInBioSource, RightParticipant, Reaction, ReactionInBioSource, ReactionInPathway WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND RightParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND ReactionInBioSource.id=ReactionInPathway.idReactionBioSource AND ReactionInPathway.idPathway IN ($P_Listid)";
$R_MetabRight=					"SELECT DISTINCT Metabolite.id AS idInBio, Metabolite.id AS id, Metabolite.name AS name, Metabolite.chemicalFormula AS chemicalFormula, Metabolite.dbIdentifier AS dbIdentifier, Metabolite.smiles AS smiles, Metabolite.caas AS caas, Metabolite.weight AS weight, Metabolite.exactNeutralMass AS exactNeutralMass, Metabolite.averageMass AS averageMass, Metabolite.generic AS generic, MetaboliteInBioSource.sideCompound AS sideCompound FROM Metabolite, MetaboliteInBioSource, RightParticipant WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource";
$R_MetabRight_idPathway=		"SELECT DISTINCT Metabolite.id AS id FROM Metabolite, MetaboliteInBioSource, RightParticipant, Reaction, ReactionInBioSource, ReactionInPathway WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite = Metabolite.id AND ReactionInBioSource.idBioSource = $P_idBioSource AND RightParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND ReactionInBioSource.id=ReactionInPathway.idReactionBioSource AND ReactionInPathway.idPathway = $P_idPathway";

/************************
**	Metabolite 
************************/
if(isset($R_MetabLeft_ListidGene) && isset($R_MetabRight_ListidGene)) {
	$R_Metabolite_ListidGene=		"($R_MetabLeft_ListidGene) UNION ($R_MetabRight_ListidGene)";
}
if(isset($R_MetabLeft_ListidProtein) && isset($R_MetabRight_ListidProtein)) {
	$R_Metabolite_ListidProtein=	"($R_MetabLeft_ListidProtein) UNION ($R_MetabRight_ListidProtein)";
}
if(isset($R_MetabLeft_ListidEnzyme) && isset($R_MetabRight_ListidEnzyme)) {
	$R_Metabolite_ListidEnzyme=		"($R_MetabLeft_ListidEnzyme) UNION ($R_MetabRight_ListidEnzyme)";
}
/*
if(isset($R_MetabLeft) && isset($R_MetabRight)) {
	$R_Metabolite=    "($R_MetabLeft) UNION ($R_MetabRight)";
}
*/
$R_Metabolite="SELECT DISTINCT MetaboliteInBioSource.idMetaboliteInBioSource AS idInBio, Metabolite.id AS id, Metabolite.name AS name, Metabolite.chemicalFormula AS chemicalFormula, Metabolite.dbIdentifier AS dbIdentifier, Metabolite.smiles AS smiles, Metabolite.caas AS caas, Metabolite.weight AS weight, Metabolite.exactNeutralMass AS exactNeutralMass, Metabolite.averageMass AS averageMass, Metabolite.generic AS generic, MetaboliteInBioSource.sideCompound AS sideCompound, MetaboliteInBioSource.boundaryCondition AS boundary, MetaboliteInBioSource.inConflictWith AS inConflictWith FROM Metabolite, MetaboliteInBioSource WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource ORDER BY name";


if(isset($R_MetabLeft_ListidMetabolite) && isset($R_MetabRight_ListidMetabolite)) {
	$R_Metabolite_ListidMetabolite=    "($R_MetabLeft_ListidMetabolite) UNION ($R_MetabRight_ListidMetabolite)";
}

if(isset($R_MetabLeft_ListidReaction) && isset($R_MetabRight_ListidReaction)) {
	$R_Metabolite_ListidReaction=	"($R_MetabLeft_ListidReaction) UNION ($R_MetabRight_ListidReaction)";
}
if(isset($R_MetabLeft_ListidPathway) && isset($R_MetabRight_ListidPathway)) {
	$R_Metabolite_ListidPathway=    "($R_MetabLeft_ListidPathway) UNION ($R_MetabRight_ListidPathway)";
}
if(isset($R_MetabLeft_idPathway) && isset($R_MetabRight_idPathway)) {
	$R_Metabolite_idPathway=    "($R_MetabLeft_idPathway) UNION ($R_MetabRight_idPathway)";
}

//$R_Metabolite_ListidMetabolite=	"SELECT DISTINCT Metabolite.id AS idInBio, Metabolite.id AS id, Metabolite.name AS name, Metabolite.chemicalFormula AS chemicalFormula, Metabolite.dbIdentifier AS dbIdentifier, Metabolite.smiles AS smiles, Metabolite.caas AS caas, Metabolite.weight AS weight, Metabolite.generic AS generic, Metabolite.idDB AS idDB, MetaboliteInBioSource.boundaryCondition AS boundaryCondition FROM Metabolite, MetaboliteInBioSource WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND Metabolite.id IN ($P_Listid)";
//$R_Metabolite=					"SELECT DISTINCT Metabolite.id AS idInBio, Metabolite.id AS id, Metabolite.name AS name, Metabolite.chemicalFormula AS chemicalFormula, Metabolite.dbIdentifier AS dbIdentifier, Metabolite.smiles AS smiles, Metabolite.caas AS caas, Metabolite.weight AS weight, Metabolite.generic AS generic, Metabolite.idDB AS idDB, MetaboliteInBioSource.boundaryCondition AS boundaryCondition FROM Metabolite, MetaboliteInBioSource WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND ( MetaboliteInBioSource.idBioSource = $P_idBioSource )";
$R_MetaboliteBiocyc=			"SELECT DISTINCT Metabolite.id AS idInBio, Metabolite.id AS id, Metabolite.name AS name, Metabolite.chemicalFormula AS chemicalFormula, Metabolite.smiles AS smiles, Metabolite.caas AS caas, Metabolite.weight AS weight, Metabolite.generic AS generic, Metabolite.idDB AS idDB, Metabolite.dbIdentifier AS dbIdentifier FROM Metabolite WHERE  Metabolite.idDB=309";


/************************
**	Enzyme 
************************/
$R_Enzyme_ListidGene=			"SELECT DISTINCT EnzymeInBioSource.id AS idInBio, Enzyme.id AS id, Enzyme.name AS name, Enzyme.dbIdentifier AS dbIdentifier FROM Enzyme, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource, GeneCodesForProtein, GeneInBioSource WHERE EnzymeInBioSource.idBioSource = $P_idBioSource AND Enzyme.id = EnzymeInBioSource.idEnzyme  AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInEnzyme.idProteinInBioSource = ProteinInBioSource.id AND ProteinInBioSource.id = GeneCodesForProtein.idProteinInBioSource AND GeneCodesForProtein.idGeneInBioSource = GeneInBioSource.id AND GeneInBioSource.idGene IN ($P_Listid)";
$R_Enzyme_ListidProtein=		"SELECT DISTINCT EnzymeInBioSource.id AS idInBio, Enzyme.id AS id, Enzyme.name AS name, Enzyme.dbIdentifier AS dbIdentifier FROM Enzyme, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource WHERE  EnzymeInBioSource.idBioSource = $P_idBioSource AND Enzyme.id = EnzymeInBioSource.idEnzyme  AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInEnzyme.idProteinInBioSource = ProteinInBioSource.id AND ProteinInBioSource.idProtein IN ($P_Listid)";
$R_Enzyme_ListidEnzyme=			"SELECT DISTINCT EnzymeInBioSource.id AS idInBio, Enzyme.id AS id, Enzyme.name AS name, Enzyme.dbIdentifier AS dbIdentifier FROM Enzyme, EnzymeInBioSource WHERE Enzyme.id = EnzymeInBioSource.idEnzyme  AND EnzymeInBioSource.idBioSource =$P_idBioSource AND Enzyme.id IN ($P_Listid)";
$R_Enzyme_ListidMetabLeft=		"SELECT DISTINCT EnzymeInBioSource.id AS idInBio, Enzyme.id AS id, Enzyme.name AS name, Enzyme.dbIdentifier AS dbIdentifier FROM Enzyme, EnzymeInBioSource, Reaction, LeftParticipant, ReactionInBioSource, Catalyses WHERE  EnzymeInBioSource.idBioSource = $P_idBioSource AND Enzyme.id = EnzymeInBioSource.idEnzyme  AND EnzymeInBioSource.id = Catalyses.idEnzymeInBioSource AND Catalyses.idReactionInBioSource= ReactionInBioSource.id AND ReactionInBioSource.idReaction = Reaction.id  AND Reaction.id = LeftParticipant.idReaction AND LeftParticipant.idMetabolite IN ($P_Listid)";
$R_Enzyme_ListidMetabRight=		"SELECT DISTINCT EnzymeInBioSource.id AS idInBio, Enzyme.id AS id, Enzyme.name AS name, Enzyme.dbIdentifier AS dbIdentifier FROM Enzyme, EnzymeInBioSource, Reaction, RightParticipant, ReactionInBioSource, Catalyses WHERE  EnzymeInBioSource.idBioSource = $P_idBioSource AND Enzyme.id = EnzymeInBioSource.idEnzyme  AND EnzymeInBioSource.id = Catalyses.idEnzymeInBioSource AND Catalyses.idReactionInBioSource= ReactionInBioSource.id AND ReactionInBioSource.idReaction = Reaction.id  AND Reaction.id = RightParticipant.idReaction AND RightParticipant.idMetabolite IN ($P_Listid)";
if(isset($R_Enzyme_ListidMetabLeft) && isset($R_Enzyme_ListidMetabRight)) {
	$R_Enzyme_ListidMetabolite=     "$R_Enzyme_ListidMetabLeft UNION $R_Enzyme_ListidMetabRight";
}
$R_Enzyme_ListidReaction=		"SELECT DISTINCT EnzymeInBioSource.id AS idInBio, Enzyme.id AS id, Enzyme.name AS name, Enzyme.dbIdentifier AS dbIdentifier FROM Enzyme, EnzymeInBioSource, Catalyses, ReactionInBioSource WHERE  EnzymeInBioSource.idBioSource = $P_idBioSource AND Enzyme.id = EnzymeInBioSource.idEnzyme  AND EnzymeInBioSource.id = Catalyses.idEnzymeInBioSource AND Catalyses.idReactionInBioSource= ReactionInBioSource.id AND ReactionInBioSource.idReaction IN ($P_Listid)";
$R_Enzyme_ListidPathway=		"SELECT DISTINCT EnzymeInBioSource.id AS idInBio, Enzyme.id AS id, Enzyme.name AS name, Enzyme.dbIdentifier AS dbIdentifier FROM Enzyme, EnzymeInBioSource, Catalyses, ReactionInBioSource, ReactionInPathway WHERE  EnzymeInBioSource.idBioSource = $P_idBioSource AND Enzyme.id = EnzymeInBioSource.idEnzyme  AND EnzymeInBioSource.id = Catalyses.idEnzymeInBioSource AND Catalyses.idReactionInBioSource= ReactionInBioSource.id AND ReactionInBioSource.id = ReactionInPathway.idReactionBioSource AND ReactionInPathway.idPathway IN ($P_Listid)";
$R_Enzyme=						"SELECT DISTINCT EnzymeInBioSource.id AS idInBio, Enzyme.id AS id, Enzyme.name AS name, Enzyme.dbIdentifier AS dbIdentifier, EnzymeInBioSource.inConflictWith AS inConflictWith FROM Enzyme, EnzymeInBioSource WHERE Enzyme.id = EnzymeInBioSource.idEnzyme  AND EnzymeInBioSource.idBioSource =$P_idBioSource ORDER BY name";
$R_Enzyme_Compart=				"SELECT DISTINCT EnzymeInBioSource.id AS idInBio, Enzyme.id AS id, Enzyme.name AS name, Enzyme.dbIdentifier AS dbIdentifier FROM Enzyme, EnzymeInBioSource, EnzymeInCompartment WHERE Enzyme.id = EnzymeInBioSource.idEnzyme  AND EnzymeInBioSource.idBioSource =$P_idBioSource";

/************************
**	Protein 
************************/
$R_Protein_ListidGene=			"SELECT DISTINCT ProteinInBioSource.id AS idInBio, Protein.id AS id, Protein.name AS name, Protein.dbIdentifier AS dbIdentifier FROM Protein, ProteinInBioSource, GeneCodesForProtein, GeneInBioSource WHERE  ProteinInBioSource.idBioSource = $P_idBioSource AND Protein.id = ProteinInBioSource.idProtein AND ProteinInBioSource.id = GeneCodesForProtein.idProteinInBioSource  AND GeneCodesForProtein.idGeneInBioSource = GeneInBioSource.id AND GeneInBioSource.idGene IN ($P_Listid)";
$R_Protein_ListidProtein=		"SELECT DISTINCT ProteinInBioSource.id AS idInBio, Protein.id AS id, Protein.name AS name, Protein.dbIdentifier AS dbIdentifier FROM Protein, ProteinInBioSource WHERE  ProteinInBioSource.idProtein = Protein.id AND ProteinInBioSource.idBioSource = $P_idBioSource AND Protein.id IN ($P_Listid)";
$R_Protein_ListidEnzyme=		"SELECT DISTINCT ProteinInBioSource.id AS idInBio, Protein.id AS id, Protein.name AS name, Protein.dbIdentifier AS dbIdentifier FROM Protein, ProteinInBioSource, ProteinInEnzyme, EnzymeInBioSource WHERE  ProteinInBioSource.idBioSource = $P_idBioSource AND Protein.id = ProteinInBioSource.idProtein AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND ProteinInEnzyme.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.idEnzyme IN ($P_Listid)";
$R_Protein_ListidMetabLeft=		"SELECT DISTINCT ProteinInBioSource.id AS idInBio, Protein.id AS id, Protein.name AS name, Protein.dbIdentifier AS dbIdentifier FROM Protein, ProteinInBioSource, Reaction, LeftParticipant, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme WHERE  ProteinInBioSource.idBioSource = $P_idBioSource AND Protein.id = ProteinInBioSource.idProtein AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND ProteinInEnzyme.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id =Catalyses.idEnzymeInBioSource AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND ReactionInBioSource.idReaction = Reaction.id AND Reaction.id = LeftParticipant.idReaction AND LeftParticipant.idMetabolite IN ($P_Listid)";
$R_Protein_ListidMetabRight=	"SELECT DISTINCT ProteinInBioSource.id AS idInBio, Protein.id AS id, Protein.name AS name, Protein.dbIdentifier AS dbIdentifier FROM Protein, ProteinInBioSource, Reaction, RightParticipant, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme WHERE  ProteinInBioSource.idBioSource = $P_idBioSource AND Protein.id = ProteinInBioSource.idProtein AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND ProteinInEnzyme.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id =Catalyses.idEnzymeInBioSource AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND ReactionInBioSource.idReaction = Reaction.id AND Reaction.id = RightParticipant.idReaction AND RightParticipant.idMetabolite IN ($P_Listid)";
if(isset($R_Protein_ListidMetabLeft) && isset($R_Protein_ListidMetabRight)) {
	$R_Protein_ListidMetabolite=	"$R_Protein_ListidMetabLeft UNION $R_Protein_ListidMetabRight";
}
$R_Protein_ListidReaction=		"SELECT DISTINCT ProteinInBioSource.id AS idInBio, Protein.id AS id, Protein.name AS name, Protein.dbIdentifier AS dbIdentifier FROM Protein, ProteinInBioSource, ProteinInEnzyme, EnzymeInBioSource, Catalyses, ReactionInBioSource WHERE  ProteinInBioSource.idBioSource = $P_idBioSource AND Protein.id = ProteinInBioSource.idProtein AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND ProteinInEnzyme.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id =Catalyses.idEnzymeInBioSource AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND ReactionInBioSource.idReaction IN ($P_Listid)";
$R_Protein_ListidPathway=		"SELECT DISTINCT ProteinInBioSource.id AS idInBio, Protein.id AS id, Protein.name AS name, Protein.dbIdentifier AS dbIdentifier FROM Protein, ProteinInBioSource, ProteinInEnzyme, EnzymeInBioSource, Catalyses, ReactionInBioSource, ReactionInPathway WHERE  ProteinInBioSource.idBioSource = $P_idBioSource AND Protein.id = ProteinInBioSource.idProtein AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND ProteinInEnzyme.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id =Catalyses.idEnzymeInBioSource AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND ReactionInBioSource.id = ReactionInPathway.idReactionBioSource AND ReactionInPathway.idPathway IN ($P_Listid)";
$R_Protein=						"SELECT DISTINCT ProteinInBioSource.id AS idInBio, Protein.id AS id, Protein.name AS name, Protein.dbIdentifier AS dbIdentifier, ProteinInBioSource.inConflictWith AS inConflictWith FROM Protein, ProteinInBioSource WHERE  ProteinInBioSource.idProtein = Protein.id AND ( ProteinInBioSource.idBioSource = $P_idBioSource ) ORDER BY name";
$R_Protein_Compart=				"SELECT DISTINCT ProteinInBioSource.id AS idInBio, Protein.id AS id, Protein.name AS name, Protein.dbIdentifier AS dbIdentifier FROM Protein, ProteinInBioSource, ProteinInCompartment WHERE  ProteinInBioSource.idProtein = Protein.id AND ( ProteinInBioSource.idBioSource = $P_idBioSource ) AND ProteinInCompartment.idProtein=Protein.id AND ProteinInCompartment.idCompartmentInBioSource IN ($P_Listid)";

/************************
**	Gene
************************/
$R_Gene_ListidGene=				"SELECT DISTINCT GeneInBioSource.id AS idInBio, Gene.id AS id, Gene.name AS name, Gene.dbIdentifier AS dbIdentifier FROM Gene, GeneInBioSource WHERE  GeneInBioSource.idGene = Gene.id AND GeneInBioSource.idBioSource = $P_idBioSource AND Gene.id IN ($P_Listid)";
$R_Gene_ListidProtein=			"SELECT DISTINCT GeneInBioSource.id AS idInBio, Gene.id AS id, Gene.name AS name, Gene.dbIdentifier AS dbIdentifier FROM Gene, GeneInBioSource, GeneCodesForProtein, ProteinInBioSource WHERE GeneInBioSource.idBioSource = $P_idBioSource AND Gene.id = GeneInBioSource.idGene AND GeneInBioSource.id = GeneCodesForProtein.idGeneInBioSource AND GeneCodesForProtein.idProteinInBioSource= ProteinInBioSource.id AND ProteinInBioSource.idProtein IN ($P_Listid)";
$R_Gene_ListidEnzyme=			"SELECT DISTINCT GeneInBioSource.id AS idInBio, Gene.id AS id, Gene.name AS name, Gene.dbIdentifier AS dbIdentifier FROM Gene, GeneInBioSource, GeneCodesForProtein, ProteinInBioSource, ProteinInEnzyme, EnzymeInBioSource WHERE GeneInBioSource.idBioSource = $P_idBioSource AND Gene.id = GeneInBioSource.idGene AND GeneInBioSource.id = GeneCodesForProtein.idGeneInBioSource AND GeneCodesForProtein.idProteinInBioSource= ProteinInBioSource.id AND ProteinInBioSource.id=ProteinInEnzyme.idProteinInBioSource AND ProteinInEnzyme.idEnzymeInBioSource=EnzymeInBioSource.id AND EnzymeInBioSource.idEnzyme IN ($P_Listid)";
$R_Gene_ListidMetabLeft=		"SELECT DISTINCT GeneInBioSource.id AS idInBio, Gene.id AS id, Gene.name AS name, Gene.dbIdentifier AS dbIdentifier FROM Gene, GeneInBioSource, GeneCodesForProtein, ProteinInBioSource, ProteinInEnzyme, EnzymeInBioSource, Catalyses, ReactionInBioSource, Reaction, LeftParticipant WHERE  GeneInBioSource.idBioSource = $P_idBioSource AND GeneInBioSource.idGene = Gene.id AND GeneInBioSource.id = GeneCodesForProtein.idGeneInBioSource AND GeneCodesForProtein.idProteinInBioSource = ProteinInBioSource.id AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND EnzymeInBioSource.id = Catalyses.idEnzymeInBioSource AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Reaction.id = ReactionInBioSource.idReaction AND LeftParticipant.idReaction = Reaction.id AND LeftParticipant.idMetabolite IN ($P_Listid)";
$R_Gene_ListidMetabRight=		"SELECT DISTINCT GeneInBioSource.id AS idInBio, Gene.id AS id, Gene.name AS name, Gene.dbIdentifier AS dbIdentifier FROM Gene, GeneInBioSource, GeneCodesForProtein, ProteinInBioSource, ProteinInEnzyme, EnzymeInBioSource, Catalyses, ReactionInBioSource, Reaction, RightParticipant WHERE  GeneInBioSource.idBioSource = $P_idBioSource AND GeneInBioSource.idGene = Gene.id AND GeneInBioSource.id = GeneCodesForProtein.idGeneInBioSource AND GeneCodesForProtein.idProteinInBioSource = ProteinInBioSource.id AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND EnzymeInBioSource.id = Catalyses.idEnzymeInBioSource AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Reaction.id = ReactionInBioSource.idReaction AND RightParticipant.idReaction = Reaction.id AND RightParticipant.idMetabolite IN ($P_Listid)";
if(isset($R_Gene_ListidMetabLeft) && isset($R_Gene_ListidMetabRight)) {
	$R_Gene_ListidMetabolite=		"$R_Gene_ListidMetabLeft UNION $R_Gene_ListidMetabRight";
}
$R_Gene_ListidReaction=			"SELECT DISTINCT GeneInBioSource.id AS idInBio, Gene.id AS id, Gene.name AS name, Gene.dbIdentifier AS dbIdentifier FROM Gene, GeneInBioSource, GeneCodesForProtein, ProteinInBioSource, ProteinInEnzyme, EnzymeInBioSource, Catalyses, ReactionInBioSource WHERE  GeneInBioSource.idBioSource = $P_idBioSource AND GeneInBioSource.idGene = Gene.id AND GeneInBioSource.id = GeneCodesForProtein.idGeneInBioSource AND GeneCodesForProtein.idProteinInBioSource = ProteinInBioSource.id AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND EnzymeInBioSource.id = Catalyses.idEnzymeInBioSource AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND ReactionInBioSource.idReaction IN ($P_Listid)";
$R_Gene_ListidPathway=			"SELECT DISTINCT GeneInBioSource.id AS idInBio, Gene.id AS id, Gene.name AS name, Gene.dbIdentifier AS dbIdentifier FROM Gene, GeneInBioSource, GeneCodesForProtein, ProteinInBioSource, ProteinInEnzyme, EnzymeInBioSource, Catalyses, ReactionInBioSource, ReactionInPathway WHERE  GeneInBioSource.idBioSource = $P_idBioSource AND GeneInBioSource.idGene = Gene.id AND GeneCodesForProtein.idGeneInBioSource = GeneInBioSource.id AND GeneCodesForProtein.idProteinInBioSource = ProteinInBioSource.id AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND ReactionInPathway.idReactionBioSource = ReactionInBioSource.id AND ReactionInPathway.idPathway IN ($P_Listid)";
$R_Gene=						"SELECT DISTINCT GeneInBioSource.id AS idInBio, Gene.id AS id, Gene.name AS name, Gene.dbIdentifier AS dbIdentifier, GeneInBioSource.inConflictWith AS inConflictWith FROM Gene, GeneInBioSource WHERE  GeneInBioSource.idGene = Gene.id AND ( GeneInBioSource.idBioSource = $P_idBioSource ) ORDER BY name";

/***********************
 * Compartment
 ************************/
$R_Compart=						"SELECT DISTINCT CompartmentInBioSource.idCompartmentInBioSource AS id ,CompartmentInBioSource.idCompartment AS idCompartment ,CompartmentInBioSource.identifier AS identifier, Compartment.name AS name , CompartmentInBioSource.inConflictWith AS inConflictWith FROM CompartmentInBioSource, Compartment WHERE CompartmentInBioSource.idCompartment= Compartment.idCompartment AND CompartmentInBioSource.idBioSource= $P_idBioSource ORDER BY identifier";
$R_Compartment=					"SELECT DISTINCT CompartmentInBioSource.idCompartmentInBioSource AS id ,CompartmentInBioSource.idCompartment AS idCompartment ,CompartmentInBioSource.identifier AS identifier, Compartment.name AS name FROM CompartmentInBioSource, Compartment WHERE CompartmentInBioSource.idCompartment= Compartment.idCompartment AND CompartmentInBioSource.idBioSource= $P_idBioSource ORDER BY identifier";

$R_Compart_ListidCompart=		"SELECT DISTINCT CompartmentInBioSource.idCompartmentInBioSource AS id ,CompartmentInBioSource.idCompartment AS idCompartment ,CompartmentInBioSource.identifier AS identifier FROM CompartmentInBioSource WHERE CompartmentInBioSource.idBioSource= $P_idBioSource AND CompartmentInBioSource.idCompartmentInBioSource IN ($P_Listid) ORDER BY identifier";
$R_Metabolite_Compart=			"SELECT DISTINCT Metabolite.id AS idInBio, Metabolite.id AS id, Metabolite.name AS name, Metabolite.chemicalFormula AS chemicalFormula, Metabolite.dbIdentifier AS dbIdentifier, Metabolite.smiles AS smiles, Metabolite.caas AS caas, Metabolite.weight AS weight, Metabolite.generic AS generic, Metabolite.idDB AS idDB, MetaboliteInBioSource.boundaryCondition AS boundaryCondition FROM Metabolite, MetaboliteInBioSource,MetaboliteInCompartment WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND ( MetaboliteInBioSource.idBioSource = $P_idBioSource ) AND MetaboliteInCompartment.idMetabolite= Metabolite.id AND MetaboliteInCompartment.idCompartmentInBioSource IN ($P_Listid)";
$R_MetaboliteGroup_Compart=		"SELECT DISTINCT GROUP_CONCAT(Metabolite.id) AS ListidMetabolite FROM Metabolite, MetaboliteInBioSource,MetaboliteInCompartment WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND ( MetaboliteInBioSource.idBioSource = $P_idBioSource ) AND MetaboliteInCompartment.idMetabolite= Metabolite.id AND MetaboliteInCompartment.idCompartmentInBioSource IN ($P_Listid)";

//

/************************
* A verifier si c'est utilise !!  SEPARATOR ','
************************/
//$R_MetabLeftAll_idReaction="SELECT DISTINCT GROUP_CONCAT(CONCAT(LeftParticipant.coeff,' ',Metabolite.name) SEPARATOR " + ") AS LeftR,  Reaction.name, Reaction.id FROM Metabolite, LeftParticipant, Reaction WHERE Reaction.id= LeftParticipant.idReaction AND LeftParticipant.idMetabolite= Metabolite.id AND Reaction.id= $P_idReaction";
//$R_MetabRightAll_idReaction="SELECT DISTINCT GROUP_CONCAT(CONCAT(RightParticipant.coeff,' ',Metabolite.name) SEPARATOR " + ") AS RightR,  Reaction.name, Reaction.id FROM Metabolite, RightParticipant, Reaction WHERE Reaction.id= RightParticipant.idReaction AND LeftParticipant.idMetabolite= Metabolite.id AND Reaction.id= $P_idReaction";
// $R_Enzyme_ListidBioSource="SELECT DISTINCT Enzyme.id AS id, Enzyme.name AS name, Enzyme.dbIdentifier AS dbIdentifier, Enzyme.dbId AS dbId, EnzymeInBioSource.idBioSource AS idBioSource, EnzymeInBioSource.idEnzyme AS idEnzyme FROM Enzyme, EnzymeInBioSource WHERE  EnzymeInBioSource.idEnzyme = Enzyme.id AND ( EnzymeInBioSource.idBioSource IN ($P_ListidBioSource) )";

/************************
**	Build Query to get all the metabolites in a biosource with their compartment and their number of reactions
**	Compartment info
************************/
$req1 = "select distinct m.id as mysqlId, m.name as cpdName, m.dbIdentifier as cpdId, m.chemicalFormula as chemicalFormula, m.weight as weight, mib.id as idInBioSource from Metabolite as m JOIN (MetaboliteInBioSource as mib) ON (m.id=mib.idMetabolite) ".
		"WHERE mib.idBioSource=$P_idBioSource";
// Number of reactions where the metabolites are involved in the left side
$req2 = "SELECT p.idMetabolite as idMetabolite, COUNT(*) as nbReactionsLeft FROM LeftParticipant as p ".
		"LEFT JOIN (Metabolite as m, ReactionInBioSource as ribs) ON (m.id = p.idMetabolite AND p.idReaction=ribs.idReaction)".
		" WHERE ribs.idBioSource='$P_idBioSource' GROUP by m.id";
// Number of reactions where the metabolites are involved in the right side
$req3 = "SELECT p.idMetabolite as idMetabolite, COUNT(*) as nbReactionsRight FROM RightParticipant as p ".
		"LEFT JOIN (Metabolite as m, ReactionInBioSource as ribs) ON (m.id = p.idMetabolite AND p.idReaction=ribs.idReaction)  ".
		"WHERE ribs.idBioSource='$P_idBioSource' GROUP by m.id";
// LEFT Join
$req4 = "SELECT x.idMetabolite as idMetabolite, x.nbReactionsLeft as nbReactionsLeft, y.nbReactionsRight as nbReactionsRight FROM ($req2) x LEFT JOIN ($req3) y ON x.idMetabolite=y.idMetabolite";
// RIght Join
$req5 = "SELECT x.idMetabolite as idMetabolite, y.nbReactionsLeft as nbReactionsLeft, x.nbReactionsRight as nbReactionsRight FROM ($req3) x LEFT JOIN ($req2) y ON x.idMetabolite=y.idMetabolite";
// Union
$req6 = "($req4) UNION ($req5)";

$R_MetaboliteInBioSource= 				"SELECT x.mysqlId as id, x.idInBioSource as idInBio, x.cpdName as name, x.cpdId as dbIdentifier, x.chemicalFormula as chemicalFormula, ".
								"y.nbReactionsLeft as numberReactionsLeft, y.nbReactionsRight as numberReactionsRight ".
								"FROM ($req1) x LEFT JOIN ($req6) y ON (x.mysqlId=y.idMetabolite)";



?>
