<?php
/***********************************************
 * Requete GROUP_CONCAT utilisees pour filtres
 ***********************************************/
/************************
**	Pathway
************************/
$R_Pathway_ListidGene=			"SELECT DISTINCT GROUP_CONCAT(DISTINCT Pathway.id) AS StringId FROM Pathway, ReactionInPathway, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource, GeneCodesForProtein, GeneInBioSource WHERE  Pathway.id=ReactionInPathway.idPathway  AND ReactionInPathway.idReactionBioSource = ReactionInBioSource.id AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND GeneCodesForProtein.idProteinInBioSource = ProteinInBioSource.id AND GeneCodesForProtein.idGeneInBioSource = GeneInBioSource.id AND ( GeneInBioSource.idGene IN ($P_Listid) AND ReactionInBioSource.idBioSource = $P_idBioSource)";
$R_Pathway_ListidProtein=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Pathway.id) AS StringId FROM Pathway, ReactionInPathway, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource WHERE  Pathway.id=ReactionInPathway.idPathway AND ReactionInPathway.idReactionBioSource = ReactionInBioSource.id AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInEnzyme.idProteinInBioSource = ProteinInBioSource.id AND ( ProteinInBioSource.idProtein IN ($P_Listid) AND ReactionInBioSource.idBioSource = $P_idBioSource)";
$R_Pathway_ListidEnzyme=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Pathway.id) AS StringId FROM Pathway, ReactionInPathway, ReactionInBioSource, Catalyses, EnzymeInBioSource WHERE  Pathway.id=ReactionInPathway.idPathway AND ReactionInPathway.idReactionBioSource = ReactionInBioSource.id AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.idEnzyme IN ($P_Listid) AND ReactionInBioSource.idBioSource = $P_idBioSource";
$R_Pathway_ListidMetabLeft=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Pathway.id) AS StringId FROM Pathway, ReactionInPathway, ReactionInBioSource, Reaction, LeftParticipant,  Metabolite, MetaboliteInBioSource WHERE  Pathway.id=ReactionInPathway.idPathway AND ReactionInPathway.idReactionBioSource = ReactionInBioSource.id AND LeftParticipant.idMetabolite = Metabolite.id AND LeftParticipant.idReaction = Reaction.id AND ReactionInBioSource.idReaction = Reaction.id AND MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idMetabolite  IN ($P_Listid) AND ReactionInBioSource.idBioSource = $P_idBioSource";
$R_Pathway_ListidMetabRight=	"SELECT DISTINCT GROUP_CONCAT(DISTINCT Pathway.id) AS StringId FROM Pathway, ReactionInPathway, ReactionInBioSource, Reaction, RightParticipant, Metabolite, MetaboliteInBioSource WHERE  Pathway.id=ReactionInPathway.idPathway AND ReactionInPathway.idReactionBioSource = ReactionInBioSource.id AND RightParticipant.idMetabolite= Metabolite.id AND RightParticipant.idReaction= Reaction.id AND ReactionInBioSource.idReaction = Reaction.id AND MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite IN ($P_Listid) AND ReactionInBioSource.idBioSource = $P_idBioSource ";
$R_Pathway_ListidReaction=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Pathway.id) AS StringId FROM Pathway, ReactionInPathway, ReactionInBioSource WHERE Pathway.id=ReactionInPathway.idPathway  AND ReactionInPathway.idReactionBioSource = ReactionInBioSource.id AND ReactionInBioSource.idReaction IN ($P_Listid) AND ReactionInBioSource.idBioSource = $P_idBioSource";
$R_Pathway_ListidPathway=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Pathway.id) AS StringId FROM Pathway, ReactionInPathway, ReactionInBioSource WHERE Pathway.id=ReactionInPathway.idPathway  AND ReactionInPathway.idReactionBioSource = ReactionInBioSource.id AND ReactionInBioSource.idBioSource = $P_idBioSource AND ReactionInPathway.idPathway IN ($P_Listid)";
$R_Pathway=						"SELECT DISTINCT GROUP_CONCAT(DISTINCT Pathway.id) AS StringId FROM Pathway, ReactionInPathway, ReactionInBioSource WHERE Pathway.id=ReactionInPathway.idPathway  AND ReactionInPathway.idReactionBioSource = ReactionInBioSource.id AND ReactionInBioSource.idBioSource = $P_idBioSource";

/************************
**	Reaction
************************/
$R_Reaction_ListidGene=			"SELECT DISTINCT GROUP_CONCAT(DISTINCT Reaction.id) AS StringId FROM Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource, GeneCodesForProtein, GeneInBioSource WHERE  Reaction.id = ReactionInBioSource.idReaction AND ReactionInBioSource.idBioSource = $P_idBioSource AND ReactionInBioSource.id = Catalyses.idReactionInBioSource AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND GeneCodesForProtein.idProteinInBioSource = ProteinInBioSource.id AND GeneCodesForProtein.idGeneInBioSource = GeneInBioSource.id AND GeneInBioSource.idGene IN ($P_Listid)";
$R_Reaction_ListidProtein=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Reaction.id) AS StringId FROM Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource WHERE  Reaction.id = ReactionInBioSource.idReaction AND ReactionInBioSource.idBioSource = $P_idBioSource AND ReactionInBioSource.id = Catalyses.idReactionInBioSource AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInEnzyme.idProteinInBioSource = ProteinInBioSource.id AND ProteinInBioSource.idProtein IN ($P_Listid)";
$R_Reaction_ListidEnzyme=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Reaction.id) AS StringId FROM Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource WHERE  Reaction.id = ReactionInBioSource.idReaction AND ReactionInBioSource.idBioSource = $P_idBioSource AND ReactionInBioSource.id = Catalyses.idReactionInBioSource AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id  AND EnzymeInBioSource.idEnzyme IN ($P_Listid)";
$R_Reaction_ListidMetabLeft=	"SELECT DISTINCT GROUP_CONCAT(DISTINCT Reaction.id) AS StringId FROM Reaction, ReactionInBioSource, Metabolite, LeftParticipant  WHERE  Reaction.id = ReactionInBioSource.idReaction AND ReactionInBioSource.idBioSource = $P_idBioSource AND Metabolite.id = LeftParticipant.idMetabolite  AND LeftParticipant.idReaction = Reaction.id  AND Metabolite.id IN ($P_Listid)";
$R_Reaction_ListidMetabRight=	"SELECT DISTINCT GROUP_CONCAT(DISTINCT Reaction.id) AS StringId FROM Reaction, ReactionInBioSource, Metabolite, RightParticipant WHERE  Reaction.id = ReactionInBioSource.idReaction AND ReactionInBioSource.idBioSource = $P_idBioSource AND Metabolite.id = RightParticipant.idMetabolite AND RightParticipant.idReaction = Reaction.id AND Metabolite.id IN ($P_Listid)";
$R_Reaction_ListidReaction=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Reaction.id) AS StringId FROM Reaction, ReactionInBioSource  WHERE  Reaction.id = ReactionInBioSource.idReaction AND ReactionInBioSource.idBioSource = $P_idBioSource AND ReactionInBioSource.idReaction IN ($P_Listid)";
$R_Reaction_ListidPathway=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Reaction.id) AS StringId FROM Reaction, ReactionInBioSource, ReactionInPathway WHERE Reaction.id = ReactionInBioSource.idReaction AND ReactionInPathway.idReactionBioSource = ReactionInBioSource.id AND ReactionInBioSource.idReaction = Reaction.id AND ReactionInPathway.idPathway IN ($P_Listid) AND ReactionInBioSource.idBioSource = $P_idBioSource";
$R_Reaction=					"SELECT DISTINCT GROUP_CONCAT(DISTINCT Reaction.id) AS StringId FROM Reaction, ReactionInBioSource  WHERE  Reaction.id = ReactionInBioSource.idReaction AND ReactionInBioSource.idBioSource = $P_idBioSource";

/************************
**	Metabolite Left
************************/
$R_MetabLeft_ListidGene=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Metabolite.id) AS StringId FROM Metabolite, MetaboliteInBioSource, LeftParticipant, Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource, GeneCodesForProtein, GeneInBioSource WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idReaction = Reaction.id AND LeftParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND LeftParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND GeneCodesForProtein.idProteinInBioSource = ProteinInBioSource.id AND GeneCodesForProtein.idGeneInBioSource = GeneInBioSource.id AND GeneInBioSource.idGene IN ($P_Listid)";
$R_MetabLeft_ListidProtein=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Metabolite.id) AS StringId FROM Metabolite, MetaboliteInBioSource, LeftParticipant, Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idMetabolite = Metabolite.id AND LeftParticipant.idReaction = Reaction.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND LeftParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND ProteinInBioSource.idProtein IN ($P_Listid)";
$R_MetabLeft_ListidEnzyme=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Metabolite.id) AS StringId FROM Metabolite, MetaboliteInBioSource, LeftParticipant, Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idMetabolite = Metabolite.id AND LeftParticipant.idReaction = Reaction.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND LeftParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.idEnzyme IN ($P_Listid)";
$R_MetabLeft_ListidReaction=	"SELECT DISTINCT GROUP_CONCAT(DISTINCT Metabolite.id) AS StringId FROM Metabolite, MetaboliteInBioSource, LeftParticipant WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND LeftParticipant.idReaction IN ($P_Listid)";
$R_MetabLeft_ListidMetabolite=	"SELECT DISTINCT GROUP_CONCAT(DISTINCT Metabolite.id) AS StringId FROM Metabolite, MetaboliteInBioSource, LeftParticipant WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND Metabolite.id IN ($P_Listid)";
$R_MetabLeft_ListidPathway=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Metabolite.id) AS StringId FROM Metabolite, MetaboliteInBioSource, LeftParticipant, Reaction, ReactionInBioSource, ReactionInPathway WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND LeftParticipant.idReaction = Reaction.id AND LeftParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND ReactionInBioSource.id=ReactionInPathway.idReactionBioSource AND ReactionInPathway.idPathway IN ($P_Listid)";
$R_MetabLeft=					"SELECT DISTINCT GROUP_CONCAT(DISTINCT Metabolite.id) AS StringId FROM Metabolite, MetaboliteInBioSource, LeftParticipant WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource";

/************************
**	Metabolite Right
************************/
$R_MetabRight_ListidGene=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Metabolite.id) AS StringId FROM Metabolite, MetaboliteInBioSource, RightParticipant, Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource, GeneCodesForProtein, GeneInBioSource WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND RightParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND GeneCodesForProtein.idProteinInBioSource = ProteinInBioSource.id AND GeneCodesForProtein.idGeneInBioSource = GeneInBioSource.id AND GeneInBioSource.idGene IN ($P_Listid)";
$R_MetabRight_ListidProtein=	"SELECT DISTINCT GROUP_CONCAT(DISTINCT Metabolite.id) AS StringId FROM Metabolite, MetaboliteInBioSource, RightParticipant, Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND RightParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND ProteinInBioSource.idProtein IN ($P_Listid)";
$R_MetabRight_ListidEnzyme=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Metabolite.id) AS StringId FROM Metabolite, MetaboliteInBioSource, RightParticipant, Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND RightParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.idEnzyme IN ($P_Listid)";
$R_MetabRight_ListidReaction=	"SELECT DISTINCT GROUP_CONCAT(DISTINCT Metabolite.id) AS StringId FROM Metabolite, MetaboliteInBioSource, RightParticipant WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND RightParticipant.idReaction IN ($P_Listid)";
$R_MetabRight_ListidMetabolite=	"SELECT DISTINCT GROUP_CONCAT(DISTINCT Metabolite.id) AS StringId FROM Metabolite, MetaboliteInBioSource, RightParticipant WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND Metabolite.id IN ($P_Listid)";
$R_MetabRight_ListidPathway=	"SELECT DISTINCT GROUP_CONCAT(DISTINCT Metabolite.id) AS StringId FROM Metabolite, MetaboliteInBioSource, RightParticipant, Reaction, ReactionInBioSource, ReactionInPathway WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND RightParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND ReactionInBioSource.id=ReactionInPathway.idReactionBioSource AND ReactionInPathway.idPathway IN ($P_Listid)";
$R_MetabRight=					"SELECT DISTINCT GROUP_CONCAT(DISTINCT Metabolite.id) AS StringId FROM Metabolite, MetaboliteInBioSource, RightParticipant WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource";

/****************************
 * Metabolite
 ****************************/
$R_Metabolite_ListidGene=		"SELECT GROUP_CONCAT(DISTINCT id) AS StringId FROM (".
									"SELECT Metabolite.id AS id FROM Metabolite, MetaboliteInBioSource, LeftParticipant, Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource, GeneCodesForProtein, GeneInBioSource WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idReaction = Reaction.id AND LeftParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND LeftParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND GeneCodesForProtein.idProteinInBioSource = ProteinInBioSource.id AND GeneCodesForProtein.idGeneInBioSource = GeneInBioSource.id AND GeneInBioSource.idGene IN ($P_Listid)".
									" UNION ".
									"SELECT Metabolite.id AS id FROM Metabolite, MetaboliteInBioSource, RightParticipant, Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource, GeneCodesForProtein, GeneInBioSource WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND RightParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND GeneCodesForProtein.idProteinInBioSource = ProteinInBioSource.id AND GeneCodesForProtein.idGeneInBioSource = GeneInBioSource.id AND GeneInBioSource.idGene IN ($P_Listid)".
								") AS StringId";

$R_Metabolite_ListidProtein=		"SELECT GROUP_CONCAT(DISTINCT id) AS StringId FROM (".
									"SELECT Metabolite.id AS id FROM Metabolite, MetaboliteInBioSource, LeftParticipant, Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idMetabolite = Metabolite.id AND LeftParticipant.idReaction = Reaction.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND LeftParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND ProteinInBioSource.idProtein IN ($P_Listid)".
									" UNION ".
									"SELECT Metabolite.id AS id FROM Metabolite, MetaboliteInBioSource, RightParticipant, Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND RightParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND ProteinInBioSource.idProtein IN ($P_Listid)".
								") AS StringId";

$R_Metabolite_ListidEnzyme=		"SELECT GROUP_CONCAT(DISTINCT id) AS StringId FROM (".
									"SELECT Metabolite.id AS id FROM Metabolite, MetaboliteInBioSource, LeftParticipant, Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idMetabolite = Metabolite.id AND LeftParticipant.idReaction = Reaction.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND LeftParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.idEnzyme IN ($P_Listid)".
									" UNION ".
									"SELECT Metabolite.id AS id FROM Metabolite, MetaboliteInBioSource, RightParticipant, Reaction, ReactionInBioSource, Catalyses, EnzymeInBioSource WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND RightParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.idEnzyme IN ($P_Listid)".
								") AS StringId";

$R_Metabolite_ListidReaction=	"SELECT GROUP_CONCAT(DISTINCT id) AS StringId FROM (".
									"SELECT Metabolite.id AS id FROM Metabolite, MetaboliteInBioSource, LeftParticipant WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND LeftParticipant.idReaction IN ($P_Listid)".
									" UNION ".
									"SELECT Metabolite.id AS id FROM Metabolite, MetaboliteInBioSource, RightParticipant WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND RightParticipant.idReaction IN ($P_Listid)".
								") AS StringId";

$R_Metabolite_ListidPathway=	"SELECT GROUP_CONCAT(DISTINCT id) AS StringId FROM (".
									"SELECT Metabolite.id AS id FROM Metabolite, MetaboliteInBioSource, LeftParticipant, Reaction, ReactionInBioSource, ReactionInPathway WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND LeftParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND LeftParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND ReactionInBioSource.id=ReactionInPathway.idReactionBioSource AND ReactionInPathway.idPathway IN ($P_Listid)".
									" UNION ".
									"SELECT Metabolite.id AS id FROM Metabolite, MetaboliteInBioSource, RightParticipant, Reaction, ReactionInBioSource, ReactionInPathway WHERE  MetaboliteInBioSource.idMetabolite = Metabolite.id AND RightParticipant.idMetabolite = Metabolite.id AND MetaboliteInBioSource.idBioSource = $P_idBioSource AND RightParticipant.idReaction = Reaction.id AND Reaction.id = ReactionInBioSource.idReaction AND ReactionInBioSource.id=ReactionInPathway.idReactionBioSource AND ReactionInPathway.idPathway IN ($P_Listid)".
								") AS StringId";

/************************
**	Enzyme 
************************/
$R_Enzyme_ListidGene=			"SELECT DISTINCT GROUP_CONCAT(DISTINCT Enzyme.id) AS StringId FROM Enzyme, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource, GeneCodesForProtein, GeneInBioSource WHERE EnzymeInBioSource.idBioSource = $P_idBioSource AND Enzyme.id = EnzymeInBioSource.idEnzyme  AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInEnzyme.idProteinInBioSource = ProteinInBioSource.id AND ProteinInBioSource.id = GeneCodesForProtein.idProteinInBioSource AND GeneCodesForProtein.idGeneInBioSource = GeneInBioSource.id AND GeneInBioSource.idGene IN ($P_Listid)";
$R_Enzyme_ListidProtein=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Enzyme.id) AS StringId FROM Enzyme, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource WHERE  EnzymeInBioSource.idBioSource = $P_idBioSource AND Enzyme.id = EnzymeInBioSource.idEnzyme  AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInEnzyme.idProteinInBioSource = ProteinInBioSource.id AND ProteinInBioSource.idProtein IN ($P_Listid)";
$R_Enzyme_ListidEnzyme=			"SELECT DISTINCT GROUP_CONCAT(DISTINCT Enzyme.id) AS StringId FROM Enzyme, EnzymeInBioSource WHERE Enzyme.id = EnzymeInBioSource.idEnzyme  AND EnzymeInBioSource.idBioSource =$P_idBioSource AND Enzyme.id IN ($P_Listid)";
$R_Enzyme_ListidMetabLeft=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Enzyme.id) AS StringId FROM Enzyme, EnzymeInBioSource, Reaction, LeftParticipant, ReactionInBioSource, Catalyses WHERE  EnzymeInBioSource.idBioSource = $P_idBioSource AND Enzyme.id = EnzymeInBioSource.idEnzyme  AND EnzymeInBioSource.id = Catalyses.idEnzymeInBioSource AND Catalyses.idReactionInBioSource= ReactionInBioSource.id AND ReactionInBioSource.idReaction = Reaction.id  AND Reaction.id = LeftParticipant.idReaction AND LeftParticipant.idMetabolite IN ($P_Listid)";
$R_Enzyme_ListidMetabRight=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Enzyme.id) AS StringId FROM Enzyme, EnzymeInBioSource, Reaction, RightParticipant, ReactionInBioSource, Catalyses WHERE  EnzymeInBioSource.idBioSource = $P_idBioSource AND Enzyme.id = EnzymeInBioSource.idEnzyme  AND EnzymeInBioSource.id = Catalyses.idEnzymeInBioSource AND Catalyses.idReactionInBioSource= ReactionInBioSource.id AND ReactionInBioSource.idReaction = Reaction.id  AND Reaction.id = RightParticipant.idReaction AND RightParticipant.idMetabolite IN ($P_Listid)";
$R_Enzyme_ListidReaction=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Enzyme.id) AS StringId FROM Enzyme, EnzymeInBioSource, Catalyses, ReactionInBioSource WHERE  EnzymeInBioSource.idBioSource = $P_idBioSource AND Enzyme.id = EnzymeInBioSource.idEnzyme  AND EnzymeInBioSource.id = Catalyses.idEnzymeInBioSource AND Catalyses.idReactionInBioSource= ReactionInBioSource.id AND ReactionInBioSource.idReaction IN ($P_Listid)";
$R_Enzyme_ListidPathway=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Enzyme.id) AS StringId FROM Enzyme, EnzymeInBioSource, Catalyses, ReactionInBioSource, ReactionInPathway WHERE  EnzymeInBioSource.idBioSource = $P_idBioSource AND Enzyme.id = EnzymeInBioSource.idEnzyme  AND EnzymeInBioSource.id = Catalyses.idEnzymeInBioSource AND Catalyses.idReactionInBioSource= ReactionInBioSource.id AND ReactionInBioSource.id = ReactionInPathway.idReactionBioSource AND ReactionInPathway.idPathway IN ($P_Listid)";
$R_Enzyme=						"SELECT DISTINCT GROUP_CONCAT(DISTINCT Enzyme.id) AS StringId FROM Enzyme, EnzymeInBioSource WHERE Enzyme.id = EnzymeInBioSource.idEnzyme  AND EnzymeInBioSource.idBioSource =$P_idBioSource";
$R_Enzyme_Compart=				"SELECT DISTINCT GROUP_CONCAT(DISTINCT Enzyme.id) AS StringId FROM Enzyme, EnzymeInBioSource, EnzymeInCompartment WHERE Enzyme.id = EnzymeInBioSource.idEnzyme  AND EnzymeInBioSource.idBioSource =$P_idBioSource";

/************************
**	Protein 
************************/
$R_Protein_ListidGene=			"SELECT DISTINCT GROUP_CONCAT(DISTINCT Protein.id) AS StringId FROM Protein, ProteinInBioSource, GeneCodesForProtein, GeneInBioSource WHERE  ProteinInBioSource.idBioSource = $P_idBioSource AND Protein.id = ProteinInBioSource.idProtein AND ProteinInBioSource.id = GeneCodesForProtein.idProteinInBioSource  AND GeneCodesForProtein.idGeneInBioSource = GeneInBioSource.id AND GeneInBioSource.idGene IN ($P_Listid)";
$R_Protein_ListidProtein=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Protein.id) AS StringId FROM Protein, ProteinInBioSource WHERE  ProteinInBioSource.idProtein = Protein.id AND ProteinInBioSource.idBioSource = $P_idBioSource AND Protein.id IN ($P_Listid)";
$R_Protein_ListidEnzyme=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Protein.id) AS StringId FROM Protein, ProteinInBioSource, ProteinInEnzyme, EnzymeInBioSource WHERE  ProteinInBioSource.idBioSource = $P_idBioSource AND Protein.id = ProteinInBioSource.idProtein AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND ProteinInEnzyme.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.idEnzyme IN ($P_Listid)";
$R_Protein_ListidMetabLeft=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Protein.id) AS StringId FROM Protein, ProteinInBioSource, Reaction, LeftParticipant, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme WHERE  ProteinInBioSource.idBioSource = $P_idBioSource AND Protein.id = ProteinInBioSource.idProtein AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND ProteinInEnzyme.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id =Catalyses.idEnzymeInBioSource AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND ReactionInBioSource.idReaction = Reaction.id AND Reaction.id = LeftParticipant.idReaction AND LeftParticipant.idMetabolite IN ($P_Listid)";
$R_Protein_ListidMetabRight=	"SELECT DISTINCT GROUP_CONCAT(DISTINCT Protein.id) AS StringId FROM Protein, ProteinInBioSource, Reaction, RightParticipant, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme WHERE  ProteinInBioSource.idBioSource = $P_idBioSource AND Protein.id = ProteinInBioSource.idProtein AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND ProteinInEnzyme.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id =Catalyses.idEnzymeInBioSource AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND ReactionInBioSource.idReaction = Reaction.id AND Reaction.id = RightParticipant.idReaction AND RightParticipant.idMetabolite IN ($P_Listid)";
$R_Protein_ListidReaction=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Protein.id) AS StringId FROM Protein, ProteinInBioSource, ProteinInEnzyme, EnzymeInBioSource, Catalyses, ReactionInBioSource WHERE  ProteinInBioSource.idBioSource = $P_idBioSource AND Protein.id = ProteinInBioSource.idProtein AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND ProteinInEnzyme.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id =Catalyses.idEnzymeInBioSource AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND ReactionInBioSource.idReaction IN ($P_Listid)";
$R_Protein_ListidPathway=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Protein.id) AS StringId FROM Protein, ProteinInBioSource, ProteinInEnzyme, EnzymeInBioSource, Catalyses, ReactionInBioSource, ReactionInPathway WHERE  ProteinInBioSource.idBioSource = $P_idBioSource AND Protein.id = ProteinInBioSource.idProtein AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND ProteinInEnzyme.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id =Catalyses.idEnzymeInBioSource AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND ReactionInBioSource.id = ReactionInPathway.idReactionBioSource AND ReactionInPathway.idPathway IN ($P_Listid)";
$R_Protein=						"SELECT DISTINCT GROUP_CONCAT(DISTINCT Protein.id) AS StringId FROM Protein, ProteinInBioSource WHERE  ProteinInBioSource.idProtein = Protein.id AND ( ProteinInBioSource.idBioSource = $P_idBioSource )";
$R_Protein_Compart=				"SELECT DISTINCT GROUP_CONCAT(DISTINCT Protein.id) AS StringId FROM Protein, ProteinInBioSource, ProteinInCompartment WHERE  ProteinInBioSource.idProtein = Protein.id AND ( ProteinInBioSource.idBioSource = $P_idBioSource ) AND ProteinInCompartment.idProtein=Protein.id AND ProteinInCompartment.idCompartmentInBioSource IN ($P_Listid)";

/************************
**	Gene
************************/
$R_Gene_ListidGene=				"SELECT DISTINCT GROUP_CONCAT(DISTINCT Gene.id) AS StringId FROM Gene, GeneInBioSource WHERE  GeneInBioSource.idGene = Gene.id AND GeneInBioSource.idBioSource = $P_idBioSource AND Gene.id IN ($P_Listid)";
$R_Gene_ListidProtein=			"SELECT DISTINCT GROUP_CONCAT(DISTINCT Gene.id) AS StringId FROM Gene, GeneInBioSource, GeneCodesForProtein, ProteinInBioSource WHERE GeneInBioSource.idBioSource = $P_idBioSource AND Gene.id = GeneInBioSource.idGene AND GeneInBioSource.id = GeneCodesForProtein.idGeneInBioSource AND GeneCodesForProtein.idProteinInBioSource= ProteinInBioSource.id AND ProteinInBioSource.idProtein IN ($P_Listid)";
$R_Gene_ListidEnzyme=			"SELECT DISTINCT GROUP_CONCAT(DISTINCT Gene.id) AS StringId FROM Gene, GeneInBioSource, GeneCodesForProtein, ProteinInBioSource, ProteinInEnzyme, EnzymeInBioSource WHERE GeneInBioSource.idBioSource = $P_idBioSource AND Gene.id = GeneInBioSource.idGene AND GeneInBioSource.id = GeneCodesForProtein.idGeneInBioSource AND GeneCodesForProtein.idProteinInBioSource= ProteinInBioSource.id AND ProteinInBioSource.id=ProteinInEnzyme.idProteinInBioSource AND ProteinInEnzyme.idEnzymeInBioSource=EnzymeInBioSource.id AND EnzymeInBioSource.idEnzyme IN ($P_Listid)";
$R_Gene_ListidMetabLeft=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Gene.id) AS StringId FROM Gene, GeneInBioSource, GeneCodesForProtein, ProteinInBioSource, ProteinInEnzyme, EnzymeInBioSource, Catalyses, ReactionInBioSource, Reaction, LeftParticipant WHERE  GeneInBioSource.idBioSource = $P_idBioSource AND GeneInBioSource.idGene = Gene.id AND GeneInBioSource.id = GeneCodesForProtein.idGeneInBioSource AND GeneCodesForProtein.idProteinInBioSource = ProteinInBioSource.id AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND EnzymeInBioSource.id = Catalyses.idEnzymeInBioSource AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Reaction.id = ReactionInBioSource.idReaction AND LeftParticipant.idReaction = Reaction.id AND LeftParticipant.idMetabolite IN ($P_Listid)";
$R_Gene_ListidMetabRight=		"SELECT DISTINCT GROUP_CONCAT(DISTINCT Gene.id) AS StringId FROM Gene, GeneInBioSource, GeneCodesForProtein, ProteinInBioSource, ProteinInEnzyme, EnzymeInBioSource, Catalyses, ReactionInBioSource, Reaction, RightParticipant WHERE  GeneInBioSource.idBioSource = $P_idBioSource AND GeneInBioSource.idGene = Gene.id AND GeneInBioSource.id = GeneCodesForProtein.idGeneInBioSource AND GeneCodesForProtein.idProteinInBioSource = ProteinInBioSource.id AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND EnzymeInBioSource.id = Catalyses.idEnzymeInBioSource AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Reaction.id = ReactionInBioSource.idReaction AND RightParticipant.idReaction = Reaction.id AND RightParticipant.idMetabolite IN ($P_Listid)";
$R_Gene_ListidReaction=			"SELECT DISTINCT GROUP_CONCAT(DISTINCT Gene.id) AS StringId FROM Gene, GeneInBioSource, GeneCodesForProtein, ProteinInBioSource, ProteinInEnzyme, EnzymeInBioSource, Catalyses, ReactionInBioSource WHERE  GeneInBioSource.idBioSource = $P_idBioSource AND GeneInBioSource.idGene = Gene.id AND GeneInBioSource.id = GeneCodesForProtein.idGeneInBioSource AND GeneCodesForProtein.idProteinInBioSource = ProteinInBioSource.id AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND EnzymeInBioSource.id = Catalyses.idEnzymeInBioSource AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND ReactionInBioSource.idReaction IN ($P_Listid)";
$R_Gene_ListidPathway=			"SELECT DISTINCT GROUP_CONCAT(DISTINCT Gene.id) AS StringId FROM Gene, GeneInBioSource, GeneCodesForProtein, ProteinInBioSource, ProteinInEnzyme, EnzymeInBioSource, Catalyses, ReactionInBioSource, ReactionInPathway WHERE  GeneInBioSource.idBioSource = $P_idBioSource AND GeneInBioSource.idGene = Gene.id AND GeneCodesForProtein.idGeneInBioSource = GeneInBioSource.id AND GeneCodesForProtein.idProteinInBioSource = ProteinInBioSource.id AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND ReactionInPathway.idReactionBioSource = ReactionInBioSource.id AND ReactionInPathway.idPathway IN ($P_Listid)";
$R_Gene=						"SELECT DISTINCT GROUP_CONCAT(DISTINCT Gene.id) AS StringId FROM Gene, GeneInBioSource WHERE  GeneInBioSource.idGene = Gene.id AND ( GeneInBioSource.idBioSource = $P_idBioSource )";

/************************
**	Compatment
************************/

$R_Compart_idProtein=		"SELECT GROUP_CONCAT(DISTINCT CompartmentInBioSource.idCompartmentInBioSource) AS CompartId FROM CompartmentInBioSource, ProteinInCompartment WHERE  ProteinInCompartment.idCompartmentInBioSource = CompartmentInBioSource.idCompartmentInBioSource AND CompartmentInBioSource.idBioSource = $P_idBioSource AND ProteinInCompartment.idProtein = $P_id";
$R_Compart_idEnzyme=		"SELECT GROUP_CONCAT(DISTINCT CompartmentInBioSource.idCompartmentInBioSource) AS CompartId FROM CompartmentInBioSource, EnzymeInCompartment WHERE  EnzymeInCompartment.idCompartmentInBioSource = CompartmentInBioSource.idCompartmentInBioSource AND CompartmentInBioSource.idBioSource = $P_idBioSource AND EnzymeInCompartment.idEnzyme = $P_id";
$R_Compart_idMetabolite=	"SELECT GROUP_CONCAT(DISTINCT CompartmentInBioSource.idCompartmentInBioSource) AS CompartId FROM CompartmentInBioSource, MetaboliteInCompartment WHERE  MetaboliteInCompartment.idCompartmentInBioSource = CompartmentInBioSource.idCompartmentInBioSource AND CompartmentInBioSource.idBioSource = $P_idBioSource AND MetaboliteInCompartment.idMetabolite = $P_id";
$R_Compart_idReaction=	"SELECT GROUP_CONCAT(DISTINCT CompartmentInBioSource.idCompartmentInBioSource) AS CompartId FROM CompartmentInBioSource, ReactionInCompartment WHERE  ReactionInCompartment.idCompartmentInBioSource = CompartmentInBioSource.idCompartmentInBioSource AND CompartmentInBioSource.idBioSource = $P_idBioSource AND ReactionInCompartment.idReaction = $P_id";
$R_Compart_idPathway=		"SELECT GROUP_CONCAT(DISTINCT CompartmentInBioSource.idCompartmentInBioSource) AS CompartId FROM CompartmentInBioSource, PathwayInCompartment WHERE  PathwayInCompartment.idCompartmentInBioSource = CompartmentInBioSource.idCompartmentInBioSource AND CompartmentInBioSource.idBioSource = $P_idBioSource AND PathwayInCompartment.idPathway = $P_id";



/************************
**	CompartmentInBioSource
************************/

$R_CompartmentInBioSource_ListidProtein=	"SELECT GROUP_CONCAT(DISTINCT CompartmentInBioSource.idCompartmentInBioSource) AS StringId FROM CompartmentInBioSource, ProteinInCompartment WHERE  ProteinInCompartment.idCompartmentInBioSource = CompartmentInBioSource.idCompartmentInBioSource AND CompartmentInBioSource.idBioSource = $P_idBioSource AND ProteinInCompartment.idProtein IN ($P_Listid)";
$R_CompartmentInBioSource_ListidEnzyme=		"SELECT GROUP_CONCAT(DISTINCT CompartmentInBioSource.idCompartmentInBioSource) AS StringId FROM CompartmentInBioSource, EnzymeInCompartment WHERE  EnzymeInCompartment.idCompartmentInBioSource = CompartmentInBioSource.idCompartmentInBioSource AND CompartmentInBioSource.idBioSource = $P_idBioSource AND EnzymeInCompartment.idEnzyme IN ($P_Listid)";
$R_CompartmentInBioSource_ListidMetabolite=	"SELECT GROUP_CONCAT(DISTINCT CompartmentInBioSource.idCompartmentInBioSource) AS StringId FROM CompartmentInBioSource, MetaboliteInCompartment WHERE  MetaboliteInCompartment.idCompartmentInBioSource = CompartmentInBioSource.idCompartmentInBioSource AND CompartmentInBioSource.idBioSource = $P_idBioSource AND MetaboliteInCompartment.idMetabolite IN ($P_Listid)";
//$R_CompartmentInBioSource_ListidReaction=		"SELECT GROUP_CONCAT(DISTINCT CompartmentInBioSource.idCompartmentInBioSource) AS StringId FROM CompartmentInBioSource, ReactionInCompartment WHERE  ReactionInCompartment.idCompartmentInBioSource = CompartmentInBioSource.idCompartmentInBioSource AND CompartmentInBioSource.idBioSource = $P_idBioSource AND ReactionInCompartment.idReaction IN ($P_Listid)";
//$R_CompartmentInBioSource_ListidPathway=		"SELECT GROUP_CONCAT(DISTINCT CompartmentInBioSource.idCompartmentInBioSource) AS StringId FROM CompartmentInBioSource, PathwayInCompartment WHERE  PathwayInCompartment.idCompartmentInBioSource = CompartmentInBioSource.idCompartmentInBioSource AND CompartmentInBioSource.idBioSource = $P_idBioSource AND PathwayInCompartment.idPathway IN ($P_Listid)";

$R_CompartmentInBioSource_ListidReactionLeftMetab	=	"SELECT DISTINCT CompartmentInBioSource.idCompartmentInBioSource AS CompartId FROM CompartmentInBioSource, MetaboliteInCompartment, LeftParticipant, Reaction WHERE MetaboliteInCompartment.idCompartmentInBioSource=CompartmentInBioSource.idCompartmentInBioSource AND LeftParticipant.idMetabolite = MetaboliteInCompartment.idMetabolite AND Reaction.id =LeftParticipant.idReaction AND CompartmentInBioSource.idBioSource = $P_idBioSource AND Reaction.id IN ($P_Listid)";
$R_CompartmentInBioSource_ListidReactionRightMetab	=	"SELECT DISTINCT CompartmentInBioSource.idCompartmentInBioSource AS CompartId FROM CompartmentInBioSource, MetaboliteInCompartment, RightParticipant, Reaction WHERE MetaboliteInCompartment.idCompartmentInBioSource=CompartmentInBioSource.idCompartmentInBioSource AND RightParticipant.idMetabolite = MetaboliteInCompartment.idMetabolite AND Reaction.id =RightParticipant.idReaction AND CompartmentInBioSource.idBioSource = $P_idBioSource AND Reaction.id IN ($P_Listid)";
$R_CompartmentInBioSource_ListidReaction=		"SELECT GROUP_CONCAT(DISTINCT t.CompartId) AS StringId FROM ($R_CompartmentInBioSource_ListidReactionLeftMetab UNION $R_CompartmentInBioSource_ListidReactionRightMetab)t";

$R_CompartmentInBioSource_ListidPathwayLeftMetab	=	"SELECT DISTINCT CompartmentInBioSource.idCompartmentInBioSource AS CompartId FROM CompartmentInBioSource, MetaboliteInCompartment, LeftParticipant, ReactionInBioSource, ReactionInPathway WHERE MetaboliteInCompartment.idCompartmentInBioSource=CompartmentInBioSource.idCompartmentInBioSource AND LeftParticipant.idMetabolite = MetaboliteInCompartment.idMetabolite AND ReactionInBioSource.idReaction =LeftParticipant.idReaction AND ReactionInPathway.idReactionBioSource=ReactionInBioSource.id AND CompartmentInBioSource.idBioSource = $P_idBioSource AND ReactionInPathway.idPathway IN ($P_Listid)";
$R_CompartmentInBioSource_ListidPathwayRightMetab	=	"SELECT DISTINCT CompartmentInBioSource.idCompartmentInBioSource AS CompartId FROM CompartmentInBioSource, MetaboliteInCompartment, RightParticipant, ReactionInBioSource, ReactionInPathway WHERE MetaboliteInCompartment.idCompartmentInBioSource=CompartmentInBioSource.idCompartmentInBioSource AND RightParticipant.idMetabolite = MetaboliteInCompartment.idMetabolite AND ReactionInBioSource.idReaction =RightParticipant.idReaction AND ReactionInPathway.idReactionBioSource=ReactionInBioSource.id AND CompartmentInBioSource.idBioSource = $P_idBioSource AND ReactionInPathway.idPathway IN ($P_Listid)";
$R_CompartmentInBioSource_ListidPathway=		"SELECT GROUP_CONCAT(DISTINCT t.CompartId) AS StringId FROM ($R_CompartmentInBioSource_ListidPathwayLeftMetab UNION $R_CompartmentInBioSource_ListidPathwayRightMetab)t";

$R_CompartmentInBioSource_ListidGeneLeftMetab	=	"SELECT DISTINCT CompartmentInBioSource.idCompartmentInBioSource AS CompartId FROM CompartmentInBioSource, MetaboliteInCompartment, LeftParticipant, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource, GeneCodesForProtein, GeneInBioSource WHERE MetaboliteInCompartment.idCompartmentInBioSource=CompartmentInBioSource.idCompartmentInBioSource AND LeftParticipant.idMetabolite = MetaboliteInCompartment.idMetabolite AND ReactionInBioSource.idReaction =LeftParticipant.idReaction AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND GeneCodesForProtein.idProteinInBioSource = ProteinInBioSource.id AND GeneCodesForProtein.idGeneInBioSource = GeneInBioSource.id AND GeneInBioSource.idGene IN ($P_Listid) AND CompartmentInBioSource.idBioSource = $P_idBioSource";
$R_CompartmentInBioSource_ListidGeneRightMetab	=	"SELECT DISTINCT CompartmentInBioSource.idCompartmentInBioSource AS CompartId FROM CompartmentInBioSource, MetaboliteInCompartment, RightParticipant, ReactionInBioSource, Catalyses, EnzymeInBioSource, ProteinInEnzyme, ProteinInBioSource, GeneCodesForProtein, GeneInBioSource WHERE MetaboliteInCompartment.idCompartmentInBioSource=CompartmentInBioSource.idCompartmentInBioSource AND RightParticipant.idMetabolite = MetaboliteInCompartment.idMetabolite AND ReactionInBioSource.idReaction =RightParticipant.idReaction AND Catalyses.idReactionInBioSource = ReactionInBioSource.id AND Catalyses.idEnzymeInBioSource = EnzymeInBioSource.id AND EnzymeInBioSource.id = ProteinInEnzyme.idEnzymeInBioSource AND ProteinInBioSource.id = ProteinInEnzyme.idProteinInBioSource AND GeneCodesForProtein.idProteinInBioSource = ProteinInBioSource.id AND GeneCodesForProtein.idGeneInBioSource = GeneInBioSource.id AND GeneInBioSource.idGene IN ($P_Listid) AND CompartmentInBioSource.idBioSource = $P_idBioSource";
$R_CompartmentInBioSource_ListidGene=		"SELECT GROUP_CONCAT(DISTINCT t.CompartId) AS StringId FROM ($R_CompartmentInBioSource_ListidGeneLeftMetab UNION $R_CompartmentInBioSource_ListidGeneRightMetab)t";


?>